<?
    // software
    $la['COPYRIGHT'] = "{$gsValues['NAME']} {$gsValues['VERSION']} &copy <a href='{$gsValues['URL_CONTACT']}' target='_blank'>{$gsValues['NAME']}</a>, 2010-2016. All rights reserved.";
    $la['CONNECT_TO'] = "Connectez-vous à {$gsValues['NAME']}";
    $la['LANGUAGE'] = 'langue';
    $la['MAP'] = 'Carte';
    $la['MOBILE_VERSION'] = 'Version Mobile';
    $la['DESKTOP_VERSION'] = 'Version PC';
    $la['PLEASE_WAIT'] = "Patientez s'il vous plaît ...";
    // software
    
    // calendar
    $la['DAY_SUNDAY_S'] = "D";
    $la['DAY_MONDAY_S'] = "L";
    $la['DAY_TUESDAY_S'] = "M";
    $la['DAY_WEDNESDAY_S'] = "M";
    $la['DAY_THURSDAY_S'] = "J";
    $la['DAY_FRIDAY_S'] = "V";
    $la['DAY_SATURDAY_S'] = "S";
    $la['MONTH_JANUARY'] = "Janvier";
    $la['MONTH_FEBRUARY'] = "Février";
    $la['MONTH_MARCH'] = "Mars";
    $la['MONTH_APRIL'] = "Avril";
    $la['MONTH_MAY'] = "Mai";
    $la['MONTH_JUNE'] = "Juin";
    $la['MONTH_JULY'] = "Juillet";
    $la['MONTH_AUGUST'] = "Août";
    $la['MONTH_SEPTEMBER'] = "Septembre";
    $la['MONTH_OCTOBER'] = "Octobre";
    $la['MONTH_NOVEMBER'] = "Novembre";
    $la['MONTH_DECEMBER'] = "Décembre";
    // calendar
    
    // units
    $la['UNIT_KPH'] = 'km/h';
    $la['UNIT_KM'] = 'km';
    $la['UNIT_M'] = 'm';
    $la['UNIT_MPH'] = 'mph';
    $la['UNIT_MI'] = 'mi';
    $la['UNIT_FT'] = 'ft';
    $la['UNIT_GALLONS'] = 'gallons';
    $la['UNIT_LITERS'] = 'litres';
    $la['UNIT_D'] = 'J';
    $la['UNIT_H'] = 'H';
    $la['UNIT_MIN'] = 'Min';
    $la['UNIT_S'] = 'S';
    $la['UNIT_OF_DISTANCE'] = 'Unité de Distance';
    $la['UNIT_OF_CAPACITY'] = 'Unité de Capacité';
    $la['UNIT_OF_TEMPERATURE'] = 'Unité de Température';
    $la['MILE'] = 'Mile';
    $la['KILOMETER'] = 'Kilomètre';
    $la['LITER'] = 'Litre';
    $la['GALLON'] = 'Gallon';
    $la['CELSIUS'] = 'Celsius';
    $la['FAHRENHEIT'] = 'Fahrenheit';
    // units
    
    // buttons
    $la['SET'] = 'Fixer';
    $la['RELOAD'] = 'Recharger';
    $la['DELETE_ALL_EVENTS'] = 'Supprimer tous les événements';
    $la['DELETE_ALL_PLACES'] = 'Supprimer tous les adresses';
    $la['IMPORT'] = 'Importer';
    $la['EXPORT'] = 'Exporter';
    $la['PLAY'] = 'Jouer';
    $la['PAUSE'] = 'Pause';
    $la['STOP'] = 'Stop';
    $la['PAN_LEFT'] = 'Pan Gauche';
    $la['PAN_RIGHT'] = 'Pan droite';
    $la['ZOOM_IN'] = 'Zoom Dans';
    $la['ZOOM_OUT'] = 'zoom Arrière';
    $la['MENU'] = 'Menu';
    $la['RECOVER'] = 'Rappeler';
    $la['YES'] = 'Oui';
    $la['NO'] = 'Non';
    $la['SEARCH'] = 'Recherher';
    $la['SHOW'] = 'Afficher';
    $la['HIDE'] = 'Cacher';
    $la['NEW'] = 'Nouveau';
    $la['SAVE'] = 'Sauvegarder';
    $la['SEND'] = 'Envoyer';
    $la['CANCEL'] = 'Fermer';
    $la['DEFAULT'] = 'Default';
    $la['EDIT'] = 'Editer';
    $la['DELETE'] = 'Supprimer';
    $la['LOGOUT'] = 'Déconnexion';
    $la['LOGIN'] = 'Connexion';
    $la['REGISTER'] = 'Enregistrer';
    $la['LOAD_GSR'] = 'Charger GSR';
    $la['EXPORT_GSR'] = 'Exporter vers GSR';
    $la['EXPORT_KML'] = 'Exporter vers KML';
    $la['EXPORT_GPX'] = 'Exporter vers GPX';
    $la['CREATE_NOW'] = 'Créer Nouveau';
    $la['SHOW_HISTORY'] = 'Afficher Historique';
    $la['DUPLICATE'] = 'Double';
    $la['CLEAR_HISTORY'] = 'Effacer Historique';
    // buttons
    
    // date and time
    $la['DATE'] = 'Date';
    $la['TIME'] = 'Temps';
    $la['TODAY'] = "Aujourd'hui";
    $la['YESTERDAY'] = 'Hier';
    $la['BEFORE_2_DAYS'] = 'Avant hier';
    $la['BEFORE_3_DAYS'] = 'Il y a 3 jours';
    $la['THIS_WEEK'] = 'Cette Semaine';
    $la['LAST_WEEK'] = 'La Semaine Dernière,';
    $la['THIS_MONTH'] = 'Ce Mois';
    $la['LAST_MONTH'] = 'Le Mois Dernier';
    $la['TIME_FROM'] = 'Début';
    $la['TIME_TO'] = 'Fin';
    $la['PERIOD'] = 'Période';
    $la['DAILY'] = 'Quotidien';
    $la['WEEKLY'] = 'Chaque Semaine';
    $la['MONTHLY'] = 'Chaque Mois';
    // date and time
    
    // location
    $la['LOCATION'] = "Localisation";
    $la['POSITION'] = "Position";
    $la['ADDRESS'] = "Addresse";
    $la['ALTITUDE'] = "Altitude";
    $la['ANGLE'] = "Angle";
    $la['SPEED'] = "Vitesse";
    $la['COORDINATES'] = "Coordonnées";
    $la['LATITUDE'] = "Latitude";
    $la['LONGITUDE'] = "Longitude";
    // location
    
    // events and alarms
    $la['NEW_EVENT'] = "Nouvel Evénement";
    $la['EVENTS'] = 'Evénements';
    $la['EVENT'] = 'Evénement';
    $la['SOUND_ALERT'] = 'Alerte Son';
    $la['SOS'] = 'SOS';
    $la['BRACELET_ON'] = 'Bracelet on';
    $la['BRACELET_OFF'] = 'Bracelet off';
    $la['MAN_DOWN'] = 'Vers Le bas';
    $la['TOW'] = 'Remorquage';
    $la['SHOCK'] = 'Choc';
    $la['OVERSPEED'] = 'Sur-Vitesse';
    $la['UNDERSPEED'] = 'Sous-vitesse';
    $la['SUDDEN_ACCELERATION'] = 'Accélération soudaine';
    $la['SUDDEN_BRAKING'] = 'Freinage brusque';
    $la['POWER_CUT'] = 'Coupure de courant';
    $la['LOW_BATTERY'] = 'Batterie faible';
    $la['NO_CONNECTION'] = 'Pas de Connexion';
    $la['SIGNAL_JAMMING'] = 'Brouillage du signal';
    $la['ZONE_IN'] = 'Dans la zone';
    $la['ZONE_OUT'] = 'ZHors de la zone';
    $la['SENSOR_CONDITION'] = 'État du Capteur';
    $la['SELECTED_ZONES'] = 'Zones sélectionnées';
    $la['EVENT_CONDITIONS'] = 'Conditions des Evénements';
    $la['ENGINE_HOURS_REACHES'] = 'Heures Moteur atteint';
    $la['ODOMETER_REACHES'] = 'Atteint kilométrique';
    $la['MESSAGE_TO_EMAIL'] = 'Message Vers e-mail';
    $la['SMS_TO_MOBILE_PHONE'] = 'SMS vers mobile';
    $la['SYSTEM_MESSAGE'] = 'System Message';
    $la['OBJECT_CONTROL'] = 'Contrôle des traceurs';
    $la['AUTO_HIDE'] = 'Auto Cache';
    $la['EVENT_PROPERTIES'] = 'Propriétés Evénements';
    $la['NO_CONNECTION_PERIOD'] = 'Pas de Connexion (min)';
    $la['NOTIFICATION_ABOUT_EVENT'] = 'Notifications à propos Evénements';
    $la['THIS_IS_EVENT_MESSAGE'] = "C'est le message  d'événements, Merci de ne pas répondre";
    $la['TRIGGER_EVENT'] = 'Cas de déclenchement';
    // events and alarms
    
    // history and reports
    $la['HISTORY'] = 'Historique';
    $la['REPORTS'] = 'Rapports';
    $la['REPORT'] = 'Rapport';
    $la['GRAPH'] = 'Graph';
    $la['MESSAGES'] = 'Messages';
    $la['STOPS'] = 'Stops';
    $la['MOVING'] = 'En mouvement';
    $la['STOPPED'] = 'Arrêté';
    $la['FILTER'] = 'Filtrer';
    $la['GENERAL_INFO'] = 'Informations Générales';
    $la['GENERAL_INFO_MERGED'] = 'Informations Générales (fusionnée)';
    $la['DRIVES_AND_STOPS'] = 'Conduite Et Arrêt';
    $la['TRAVEL_SHEET'] = 'Feuille de Voyage';
    $la['OVERSPEEDS'] = 'Sur-Vitesse';
    $la['UNDERSPEEDS'] = 'Sous-vitesse';
    $la['ZONE_IN_OUT'] = 'Zone entré/sortie';
    $la['FUEL_FILLINGS'] = 'Remplissages de carburant';
    $la['FUEL_THEFTS'] = 'Vols de carburant';
    $la['SCHEDULE'] = 'Calendrier';
    $la['LENGTH'] = 'longueur';
    $la['ROUTE_LENGTH'] = "longueur du trajet ";
    $la['ROUTE_START'] = 'Départ';
    $la['ROUTE_END'] = 'Arrivée';
    $la['TOP_SPEED'] = 'Vitesse maximale';
    $la['AVG_SPEED'] = 'Vitesse moyenne';
    $la['STOP_DURATION'] = "Durée d'Arrêt";
    $la['MOVE_DURATION'] = 'Durée de Movement';
    $la['DURATION'] = 'Durée';
    $la['ENGINE_WORK'] = 'Travail du moteur';
    $la['ENGINE_IDLE'] = 'Ralenti du moteur';
    $la['POSITION_A'] = 'Lieu de départ';
    $la['POSITION_B'] = "Lieu d'arrivée";
    $la['ZONE_POSITION'] = 'Position Zone';
    $la['STOP_POSITION'] = "Position d'Arrét";
    $la['EVENT_POSITION'] = "Position d'evénement";
    $la['OVERSPEED_COUNT'] = 'Sur-vitesse';
    $la['OVERSPEED_POSITION'] = 'Position de Sur-vitesse';
    $la['UNDERSPEED_POSITION'] = 'Position de Sous-vitesse';
    $la['SHOW_ADDRESSES'] = 'Afficher addresses';
    $la['SPEED_LIMIT'] = 'limit Vitesse';
    $la['TIME_PERIOD'] = 'Période';
    $la['THIS_IS_REPORT_MESSAGE'] = "C'est un message de rapport , Merci de ne pas répondre";
    $la['AFTER'] = 'Aprés';
    $la['BEFORE'] = 'Avant';
    $la['STOLEN'] = 'Volé';
    $la['FILLED'] = 'Rempli';
    $la['CAME'] = "Entré";
    $la['LEFT'] = "Quitté";
    $la['ARE_YOU_SURE_YOU_WANT_TO_CLEAR_HISTORY_EVENTS'] = "Etes-vous sûr de vouloir effacer cet historique et les événements ?";
    // history and reports
    
    // account and personal
    $la['EXPIRING_OBJECTS'] = 'Objets Expirés';
    $la['SOME_OBJECTS_WILL_EXPIRE_SOON'] = 'Certains de vos activation des objets va bientôt expirer.';
    $la['PLEASE_LOGIN_INTO_ACCOUNT_FOR_MORE_DETAILS'] = "S'il vous plaît , Vous connectez avec compte pour plus de détails.";
    $la['PLEASE_PURCHASE_ACCESS_TO'] = "Si vous souhaitez continuer à utiliser notre service, s'il vous plaît acheter l'accès à";
    $la['AT_OUR_SHOP'] = 'Notre Boutique :';
    $la['REGISTRATION'] = 'Inscription';
    $la['LOGIN_DATA_WILL_BE_SENT_TO_EMAIL'] = "Données de connexion seront envoyées à l'adresse e-mail indiquée.";
    $la['REGISTRATION_SUCCESSFUL'] = "Inscription réussie.";
    $la['THANK_YOU_FOR_REGISTERING_AT'] = "Merci de votre insciptione sur {$gsValues['NAME']}.";
    $la['THIS_EMAIL_ALREADY_EXISTS'] = 'Cet E-mail existe déjà.';
    $la['USERNAME_PASSWORD_SENT'] = "Nom d'utilisateur et mot de passe envoyés.";
    $la['REGISTRATION_AT'] = "Inscription à{$gsValues['NAME']}";
    $la['ACCESS_TO_GPS_SERVER_ACCOUNT'] = 'Accès au serveur de GPS';
    $la['LOST_LOGIN_RECOVERY'] = 'Identifiants oublié?';
    $la['ENTER_USERNAME_AND_PASSWORD_TO_LOGIN'] = "Entrez le nom d'utilisateur et le mot de passe pour vous connecter.";
    $la['NEW_LOGIN_DATA_WILL_BE_SENT_TO_EMAIL'] = "Vos identifiants de connexion seront envoyés à l'adresse e-mail indiquée.";
    $la['THIS_EMAIL_IS_NOT_REGISTERED'] = "Cette adresse E-mail n'est pas enregistré.";
    $la['LOST_LOGIN_RECOVERY_TO'] = "Perdu la récupération de connexion à {$gsValues['NAME']}";
    $la['YOUR_ACCOUNT_IS_LOCKED'] = "Votre compte est verrouillé. S'il vous plaît contactez-nous via {$gsValues['EMAIL']}.";
    $la['USERNAME_OR_PASSWORD_INCORRECT'] = "Nom d'utilisateur ou mot de passe est incorrect.";
    $la['PLEASE_CHECK_YOUR_EMAIL'] = "S'il vous plaît vérifier votre e-mail.";
    $la['EMAIL'] = 'E-mail';
    $la['USERNAME'] = "Nom d'Utilisateur";
    $la['PASSWORD'] = 'Mot de Passe';
    $la['SETTINGS'] = 'Paramètres';
    $la['USER'] = 'Utilisateur';
    $la['PRIVILEGES'] = "Privilèges";
    $la['PHONE'] = 'Téléphone';
    $la['COMPANY'] = 'Société';
    $la['CITY'] = 'Ville';
    $la['CONTACT_INFO'] = 'Contact';
    $la['NAME_SURNAME'] = 'Prénom,Nom';
    $la['POST_CODE'] = 'Code Postal';
    $la['COUNTRY_STATE'] = 'Département / Etat';
    $la['PHONE_NUMBER_1'] = 'Téléphone 1';
    $la['PHONE_NUMBER_2'] = 'Téléphone 2';
    $la['CHANGE_PASSWORD'] = "Changer le Mot de Passe";
    $la['OLD_PASSWORD'] = "Ancien Mot de Passe";
    $la['NEW_PASSWORD'] = "Nouveau Mot de Passe";
    $la['REPEAT_NEW_PASSWORD'] = "Retapez le Mot de Passe";
    $la['MY_ACCOUNT'] = 'Mon Compte';
    $la['SUB_ACCOUNTS'] = 'SousComptes';
    $la['SUB_ACCOUNT'] = 'Sous Compte';
    $la['EMAIL_ADDRESS'] = 'Address E-mail';
    $la['PHONE_NUMBER_WITH_CODE'] = 'Numéro Téléphone avec Code';
    $la['REMEMBER_ME'] = 'Se Souvenir de moi';
    $la['SELECTED_OBJECTS'] = 'Traceurs Sélectionnés';
    $la['SUB_ACCOUNT_PROPERTIES'] = 'Propriétés Sous Compte';
    $la['SUB_ACCOUNTS_CAN_SPLIT_THIS_ACCOUNT_INTO_MULTIPLE_SMALLER_ACCOUNTS'] = 'Sous-comptes peuvent partager ce compte en plusieurs petits comptes avec des privilèges limités.';
    $la['CONTACT_ADMIN_IF_YOU_WANT_TO_DO_ANY_CHANGES'] = "Contactez l'administrateur si vous voulez faire des changements avec vos objets.";
    $la['NEWLY_ADDED_GPS_OBJECTS_CAN_BE_USED_FOR'] = "Objets GPS nouvellement ajoutés peuvent être utilisées pour {$gsValues['OBJ_TRIAL_PERIOD']} jours gratuits";
    $la['YOU_CAN_ADD'] = 'Vous Pouvez Ajouter';
    $la['GPS_OBJECTS_TILL'] = "Objets GPS Jusqu'à";
    $la['EXPAND_THIS_LIMIT_IN_OUR_SHOP'] = "Agrandir cette limite dans notre <a href='{$gsValues['URL_SHOP']}' target='_blank'>shop</a>."; 
    $la['YOU_CAN_ADD_UNLIMITED_NUMBER_OF_GPS_OBJECTS_TILL'] = "Vous pouvez ajouter un nombre illimité d'objets GPS jusqu'à";
    $la['YOUR_SESSION_HAS_EXPIRED'] = "Votre session a expiré. s'il vous plaît<a href='{$gsValues['URL_LOGIN']}'>login</a> encore.";
    $la['SMS'] = "SMS";
    // account and personal
    
    // object
    $la['SEND_COMMAND'] = 'Envoyer commande';
    $la['OBJECT_LIST'] = 'List des Traceurs';
    $la['OBJECT'] = 'Traceur';
    $la['OBJECTS'] = 'Traceurs';
    $la['IMEI'] = 'IMEI';
    $la['COMMAND'] = 'Commande';
    $la['COMMANDS'] = 'Commandes';
    $la['COMMANDS_STATUS'] = 'Status de la Commande';
    $la['COMMAND_PROPERTIES'] = 'Propriété de la Commande';
    $la['GROUP'] = 'Groupe';
    $la['DRIVER'] = 'Chauffeur';
    $la['ODOMETER'] = 'Odomètre';
    $la['ABSOLUTE_ODOMETER'] = 'Odomètre Absolu';
    $la['RELATIVE_ODOMETER'] = 'Odomètre relatif';
    $la['ABSOLUTE_ENGINE_HOURS'] = 'Heures de moteur absolue';
    $la['RELATIVE_ENGINE_HOURS'] = 'Relatif moteur heures';
    $la['SUMMER_RATE'] = "Taux d'été";
    $la['WINTER_RATE'] = "Taux d'hiver";
    $la['WINTER_FROM'] = 'Hiver à partir du (mois, jour)';
    $la['WINTER_TO'] = 'Hiver (mois, jour)';
    $la['TRANSPORT_MODEL'] = 'Modèle de véhicule';
    $la['PLATE_NUMBER'] = 'Immatriculation';
    $la['SIM_CARD_NUMBER'] = 'Carte SIM';
    $la['ENGINE_HOURS'] = 'Heures moteur';
    $la['GPS_DEVICE'] = 'Dispositifs GPS';
    $la['FUEL_CONSUMPTION'] = 'Consommation de carburant';
    $la['AVAILABLE_OBJECTS'] = 'Traceurs disponibles';
    $la['SENSOR'] = 'Capteur';
    $la['SENSORS'] = 'Capteurs';
    $la['SENSOR_PROPERTIES'] = 'Propriété Capteur';
    $la['IGNITION_ACC'] = 'Allumage (ACC)';
    $la['DIGITAL_INPUT'] = 'Entré Digital';
    $la['DIGITAL_OUTPUT'] = 'Sortie Digital';
    $la['FUEL_LEVEL'] = 'Niveau de carburant';
    $la['PARAMETER'] = 'Paramétres';
    $la['UNITS_OF_MEASUREMENT'] = 'Unités de mesure';
    $la['IF_SENSOR_1'] = 'Si Capteur "1" (text)';
    $la['IF_SENSOR_0'] = 'Si Capteur "0" (text)';
    $la['LOWEST_VALUE'] = 'Valeur la plus basse';
    $la['HIGHEST_VALUE'] = 'Valeur la plus haute';
    $la['FORMULA'] = 'Formule';
    $la['ACCURACY'] = 'Précision';
    $la['DETECT_STOPS_USING'] = 'Détecter les Arrêts';
    $la['MIN_MOVING_SPEED'] = 'Min. la vitesse de Mouvement en km / h (affecte arrêts et suivre la précision, par défaut 6)';
    $la['MIN_DIFF_BETWEEN_POINTS'] = 'Min. différence entre track points (élimine la dérive, par défaut 0,0005)';
    $la['MIN_GPSLEV_VALUE'] = 'Mini. valeur gps lev (élimine la dérive, par défaut 5)';
    $la['MAX_HDOP_VALUE'] = 'Max. valeur  hdop (élimine la dérive, par défaut 3)';
    $la['MIN_FF'] = "Min. différence de carburant pour détecter garnitures de carburant (par défaut 10)";
    $la['MIN_FT'] = "Min. différence de carburant pour détecter les vols de carburant (par défaut 10)";
    $la['SERVICE'] = 'Service';
    $la['SERVICE_PROPERTIES'] = 'Propriété Service';
    $la['ODOMETER_INTERVAL'] = 'Interval Odométre';
    $la['ENGINE_HOURS_INTERVAL'] = "Intervalle d'heures de moteur";
    $la['DAYS_INTERVAL'] = "Jours d'intervalle";
    $la['LAST_SERVICE'] = 'Dernier Service';
    $la['CURRENT_OBJECT_COUNTERS'] = "Compteurs d'objets courants";
    $la['CURRENT_ODOMETER'] = 'Compteur kilométrique';
    $la['CURRENT_ENGINE_HOURS'] = 'Heures de moteur actuels';
    $la['OBJECT_DRIVER_LIST'] = "Liste des Chauffeurs de l'objet";
    $la['OBJECT_DRIVER_PROPERTIES'] = "Propriétés du Chauffeur d'objet";
    $la['OBJECT_GROUP_LIST'] = "Liste des groupes d'objets";
    $la['OBJECT_GROUP_PROPERTIES'] = "Propriétés du groupe d'objets";
    $la['FIT_OBJECTS_ON_MAP'] = 'Fit objets sur la carte';
    $la['NO_OBJECTS'] = "Pas de traceur";
    $la['LOGIC'] = 'Logique';
    $la['STRING'] = 'Chaîne';
    $la['PERCENTAGE'] = 'Pourcentage';
    $la['PARAMETERS'] = "Paramètres";
    $la['MODEL'] = "Modèle";
    $la['PLATE'] = "Immatriculation";
    $la['NO_DRIVER'] = " Pas de chauffeur";
    $la['ACTIVE_TILL'] = "Activer jusqu'à";
    $la['DRIVER_INFO'] = "Information Chauffeur";  
    $la['CHECK_GPS_SIGNAL'] = 'vérifier le Signal GPS';
    $la['NO_DATA'] = "Pas de donnée";
    $la['NO_DATA_HAS_BEEN_RECEIVED_YET'] = "Aucune donnée n'a encore été reçue de du traceur.";
    $la['SENSOR_PARAMETERS_ARE_NOT_DETECTED_FOR_THIS_GPS_DEVICE'] = "Paramètres du capteur ne sont pas encore détectés pour cet appareil GPS.";
    $la['AT_LEAST_ONE_OBJECT_SELECTED'] = 'Au moins un objet doit être sélectionné..';
    $la['COMMAND_SENT_FOR_EXECUTION'] = "Commande envoyée avec succès.";
    $la['INACTIVE_OBJECTS'] = " Traceurs Inactifs";
    $la['THERE_ARE_INACTIVE_OBJECTS_IN_YOUR_ACCOUNT'] = 'Il ya des traceurs inactifs dans votre compte. Allez à <a href="#" onclick="settingsOpen();">settings</a> Pour plus de détails.';
    $la['EXPIRING_OBJECTS'] = "Traceurs ";
    $la['SOME_OF_YOUR_OBJECTS_ACTIVATION_WILL_EXPIRE_SOON'] = 'Certains de vos activation des objets va bientôt expirer. allez à<a href="#" onclick="settingsOpen();">settings</a> pour plus de détails.';
    // object
    
    // places
    $la['PLACES'] = 'Adresses';
    $la['ZONES'] = 'Zones';
    $la['MARKERS'] = 'Marqueurs';
    $la['ZONE_NAME'] = 'Nom de Zone';
    $la['MARKER_PROPERTIES'] = 'propriété Marqueur';
    $la['MARKER_VISIBLE'] = 'Marqueur Visible';
    $la['ZONE_PROPERTIES'] = 'Propriété';
    $la['ZONE_VISIBLE'] = 'Zone Visible';
    $la['NAME_VISIBLE'] = 'Nom Visible';
    $la['AVAILABLE_ZONES'] = 'Zones Disponibles';
    $la['AVAILABLE_MARKERS'] = 'Marqueurs disponibles';
    $la['ADD_ZONE'] = 'Ajouter Zone';
    $la['ADD_MARKER'] = 'Ajouter Marqueur';
    $la['NEW_ZONE'] = 'Nouvelle Zone';
    $la['NEW_MARKER'] = 'Nouveau Marqueur';  
    $la['NEAREST_ZONE'] = "Zone la plus proche";
    $la['NEAREST_MARKER'] = "Marqueur le plus proche";
    $la['AT_LEAST_ONE_ZONE_SELECTED'] = 'Au moins une zone doit être sélectionnée.';
    $la['DRAW_ZONE_ON_MAP_BEFORE_SAVING'] = "Dessinez une zones sur la carte avant d'enregistrer.";
    $la['PLACE_MARKER_ON_MAP_BEFORE_SAVING'] = "Placez le marqueur sur la carte avant de l'enregistrer.";
    // places
    
    // settings
    $la['TIMEZONE'] = 'Temps Zone';    
    $la['REMEMBER_MAP_POSITION'] = 'Rappelez-vous la dernière position sur la carte';
    $la['SHOW_OBJECT_TAIL'] = 'Afficher Objet Queue';
    $la['OBJECT_TAIL_COLOR'] = 'Couleur Traceur';
    $la['HISTORY_ROUTE_COLOR'] = "Couleur Histoire de l'itinéraire";
    $la['HISTORY_ROUTE_HIGHLIGHT_COLOR'] = 'Histoire itinéraire couleur de surbrillance';
    $la['SHOWN_ICON_ON_MAP'] = "Afficher l'icône sur la carte";
    $la['ADD_OBJECT'] = 'Ajouter Traceur';
    $la['EDIT_OBJECT'] = 'Editer Traceur';
    $la['DUPLICATE_OBJECT'] = 'Dupliquer le traceur';
    $la['SELECT_ICON'] = "Sélectionner  l'icône";
    $la['USER_INTERFACE'] = 'Interface Utilisateur';
    $la['CHANGES_SAVED_SUCCESSFULLY'] = 'Modifications enregistrées avec succès.';
    $la['SETTINGS_NOT_SAVED'] = 'Réglages non Enregistrés.';
    $la['PASSWORD_CANT_BE_EMPTY'] = "Le mot de passe ne peut pas être vide.";
    $la['INCORRECT_PASSWORD'] = "Mot de passe incorrect.";
    $la['REPEATED_PASSWORD_IS_INCORRECT'] = "Le mot de passe est incorrect.";
    $la['PASSWORD_LENGHT_AT_LEAST'] = "Le mot de passe doit être d'au moins 6 caractères.";
    // settings
    
    // other
    $la['LOADING'] = 'Chargement en cours ...';
    $la['ADD'] = 'Ajouter';
    $la['SYSTEM'] = 'Système';
    $la['CREATE'] = 'Créer';
    $la['HELLO'] = 'Bonjour';
    $la['CUSTOM'] = 'Coutume';
    $la['MAIN'] = 'Principal';
    $la['NAME'] = 'Nom';
    $la['COLOR'] = 'Couleur';
    $la['ICON'] = 'Icône';
    $la['TYPE'] = 'Type';
    $la['RESULT'] = 'Résultat';
    $la['ABOUT'] = 'A Propos';
    $la['HELP'] = 'Aide';
    $la['RULER'] = 'Règle';
    $la['DESCRIPTION'] = 'Description';
    $la['FORMAT'] = 'Format';
    $la['UNGROUPED'] = 'Non Regroupés';
    $la['PER'] = 'Par';
    $la['ACTIVATE'] = 'Activer';
    $la['ACTIVE'] = 'Actif';
    $la['ARROW'] = 'Flèche';
    $la['OTHER'] = 'Autre';
    $la['STATUS'] = 'Etat';
    $la['TOTAL'] = 'Total';
    $la['START'] = 'Début';
    $la['END'] = 'Fin';
    $la['SEND_TO_EMAIL'] = 'Envoyer vers e-mail';
    $la['ENTER_CODE'] = 'Saisir le code';
    $la['SHOW_POINT'] = 'Afficher Point';
    $la['ADDRESS_SEARCH'] = 'Chercher Addresse';
    $la['ID_NUMBER'] = 'Numéro ID';
    $la['CANT_SEND_EMAIL'] = "Vous ne pouvez pas envoyer d'E-mail.";
    $la['CONTACT_ADMINISTRATOR'] = "Contacter l'administrateur.";
    $la['NOTHING_HAS_BEEN_FOUND_ON_YOUR_REQUEST'] = "Rien n'a été trouvé sur votre demande.";
    $la['HOLD_CTRL_TO_SELECT_MULTIPLE_ITEMS'] = 'Maintenez la touche "Ctrl" pour sélectionner plusieurs éléments';
    $la['SECURITY_CODE_IS_INCORRECT'] = 'Le code de sécurité est incorrect.';
    $la['ODOMETER_LEFT'] = 'Kilométrage Gauche';
    $la['ODOMETER_EXPIRED'] = 'Kilométrage Expiré';
    $la['ENGINE_HOURS_LEFT'] = 'Heures moteur Gauche';
    $la['ENGINE_HOURS_EXPIRED'] = 'Heures moteur expiré';
    $la['DAYS_LEFT'] = 'Jours restants';
    $la['DAYS_EXPIRED'] = 'Jours Expirés';
    $la['DATA'] = "Donnée";
    $la['VALUE'] = "Valeur";
    $la['GENERAL'] = "Géneral";
    $la['INFORMATION'] = "Information";
    $la['ERROR'] = "Erreur";
    // other
    
    // invalid messages
    $la['INTERVAL_VALUE_SHOULD_BE_GREATER_THAN_LEFT_VALUE'] = "'Intervalle «valeur doit être supérieure à la« valeur de gauche ».";
    $la['THERE_IS_NO_SUCH_OBJECT_IN_YOUR_ACCOUNT'] = "Il n'y a aucun objet dans votre compte.";
    $la['INVALID_FILE_FORMAT'] = "Format de fichier incorrect.";    
    $la['THIS_EMAIL_IS_NOT_VALID'] = "Cet E-mail n'est pas valide.";
    $la['COMMAND_HEX_NOT_VALID'] = "Format HEX de commande n'est pas valide.";
    $la['NAME_CANT_BE_EMPTY'] = "Nom ne peut pas être vide.";
    $la['THIS_IMEI_IS_NOT_VALID'] = "IMEI ne peut pas être vide";
    $la['COMMAND_CANT_BE_EMPTY'] = "Commande ne peut pas être vide";
    $la['SPEED_LIMIT_CANT_BE_EMPTY'] = "Vitesse  limite ne peut pas être vide .";
    $la['ALL_AVAILABLE_FIELDS_SHOULD_BE_FILLED_OUT'] = "Tous les champs disponibles devraient être remplis.";
    $la['THIS_IMEI_ALREADY_EXISTS'] = "Cette IMEI existe deja.";
    $la['YOU_HAVE_REACHED_THE_LIMIT_OF_OBJECTS'] = "Vous avez atteint la limite d'objets.";
    $la['THIS_ACCOUNT_HAS_NO_PRIVILEGES_TO_DO_THAT'] = "Ce compte n'a pasle droit de réaliser des modifications.";
    $la['NOTHING_HAS_BEEN_FOUND'] = "Rien n'a été trouvé sur votre demande.";
    $la['NOTHING_HAS_BEEN_FOUND_TO_IMPORT'] = "Rien n'a été trouvé à importer.";
    $la['IMPORT_FILE_IS_TOO_BIG'] = "Importer un fichier est trop gros.";
    $la['IGNITION_SENSOR_IS_ALREADY_AVAILABLE'] = "Capteur d'allumage est déjà disponible.";
    // invalid messages
    
    // questions
    $la['ARE_YOU_SURE_YOU_WANT_TO_OVERWRITE_SELECTED_COMMAND'] = "Etes-vous sûr de vouloir écraser la commande sélectionné?";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE_ALL_EVENTS'] = "Etes-vous sûr de vouloir supprimer tous les événements?";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE_ALL_PLACES'] = "Etes-vous sûr que vous voulez supprimer tous les lieux?";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE'] = "Etes-vous sûr de vouloir supprimer ";
    $la['ZONES_FOUND'] = 'Zones Trouvées';
    $la['MARKERS_FOUND'] = 'Marqueurs Trouvés.';
    $la['ARE_YOU_SURE_YOU_WANT_TO_IMPORT'] = " Etes-vous sûr que vous voulez importer?";
    // questions
?>