<?
    // software
    $la['COPYRIGHT'] = "{$gsValues['NAME']} {$gsValues['VERSION']} &copy <a href='{$gsValues['URL_CONTACT']}' target='_blank'>{$gsValues['NAME']}</a>, 2010-2016. Все права защищены.";
    $la['CONNECT_TO'] = "Подключиться к {$gsValues['NAME']}";
    $la['LANGUAGE'] = 'Язык';
    $la['MAP'] = 'Карта';
    $la['MOBILE_VERSION'] = 'Мобильная версия';
    $la['DESKTOP_VERSION'] = 'Десктопная версия';
    $la['PLEASE_WAIT'] = 'Подождите...';
    // software
    
    // calendar
    $la['DAY_SUNDAY_S'] = "Вс";
    $la['DAY_MONDAY_S'] = "Пн";
    $la['DAY_TUESDAY_S'] = "Вт";
    $la['DAY_WEDNESDAY_S'] = "Ср";
    $la['DAY_THURSDAY_S'] = "Чт";
    $la['DAY_FRIDAY_S'] = "Пт";
    $la['DAY_SATURDAY_S'] = "Сб";
    $la['MONTH_JANUARY'] = "Январь";
    $la['MONTH_FEBRUARY'] = "Февраль";
    $la['MONTH_MARCH'] = "Март";
    $la['MONTH_APRIL'] = "Апрель";
    $la['MONTH_MAY'] = "Май";
    $la['MONTH_JUNE'] = "Июнь";
    $la['MONTH_JULY'] = "Июль";
    $la['MONTH_AUGUST'] = "Август";
    $la['MONTH_SEPTEMBER'] = "Сентябрь";
    $la['MONTH_OCTOBER'] = "Октябрь";
    $la['MONTH_NOVEMBER'] = "Ноябрь";
    $la['MONTH_DECEMBER'] = "Декабрь";
    // calendar
    
    // units
    $la['UNIT_KPH'] = 'км/ч';
    $la['UNIT_KM'] = 'км';
    $la['UNIT_M'] = 'м';
    $la['UNIT_MPH'] = 'ми/ч';
    $la['UNIT_MI'] = 'ми';
    $la['UNIT_FT'] = 'фт';
    $la['UNIT_GALLONS'] = 'галлонов';
    $la['UNIT_LITERS'] = 'литров';
    $la['UNIT_D'] = 'д';
    $la['UNIT_H'] = 'ч';
    $la['UNIT_MIN'] = 'мин';
    $la['UNIT_S'] = 'с';
    $la['UNIT_OF_DISTANCE'] = 'Единица расстояния';
    $la['UNIT_OF_CAPACITY'] = 'Единица емкости';
    $la['UNIT_OF_TEMPERATURE'] = 'Единица температуры';
    $la['MILE'] = 'Миля';
    $la['KILOMETER'] = 'Километр';
    $la['LITER'] = 'Литр';
    $la['GALLON'] = 'Галлон';
    $la['CELSIUS'] = 'Цельсий';
    $la['FAHRENHEIT'] = 'Фаренгейт';
    // units
    
    // buttons
    $la['SET'] = 'Установ.';
    $la['RELOAD'] = 'Перезагрузить';
    $la['DELETE_ALL_EVENTS'] = 'Удалить все события';
    $la['DELETE_ALL_PLACES'] = 'Удалить все места';
    $la['IMPORT'] = 'Импорт';
    $la['EXPORT'] = 'Экспорт';
    $la['PLAY'] = 'Играть';
    $la['PAUSE'] = 'Пауза';
    $la['STOP'] = 'Стоп';
    $la['PAN_LEFT'] = 'Пан в лево';
    $la['PAN_RIGHT'] = 'Пан в право';
    $la['ZOOM_IN'] = 'Увеличить';
    $la['ZOOM_OUT'] = 'Уменьшить';
    $la['MENU'] = 'Меню';
    $la['RECOVER'] = 'Напомнить';
    $la['YES'] = 'Да';
    $la['NO'] = 'Нет';
    $la['SEARCH'] = 'Поиск';
    $la['SHOW'] = 'Показать';
    $la['HIDE'] = 'Прятать';
    $la['NEW'] = 'Новый';
    $la['SAVE'] = 'Сохранить';
    $la['SEND'] = 'Отправить';
    $la['CANCEL'] = 'Отменить';
    $la['DEFAULT'] = 'По умолчанию';
    $la['EDIT'] = 'Свойства';
    $la['DELETE'] = 'Удалять';
    $la['DELETE_ALL'] = 'Удалить все';    
    $la['LOGOUT'] = 'Выйти';
    $la['LOGIN'] = 'Логин';
    $la['REGISTER'] = 'Зарегистрироваться';
    $la['LOAD_GSR'] = 'Загрузить GSR';
    $la['EXPORT_GSR'] = 'Экспорт в GSR';
    $la['EXPORT_KML'] = 'Экспорт в KML';
    $la['EXPORT_GPX'] = 'Экспорт в GPX';
    $la['GENERATE_REPORT'] = 'Создать отчёт';
    $la['CREATE_NOW'] = 'Создать сейчас';
    $la['SHOW_HISTORY'] = 'Показать историю';
    $la['DUPLICATE'] = 'Дублировать';
    $la['CLEAR_HISTORY'] = 'Удалить историю';
    $la['IMAGE_GALLERY'] = 'Галерея фотографий';
    $la['CHAT'] = 'Чат';
    // buttons
    
    // date and time
    $la['TIME_SERVER'] = 'Время (сервер)';
    $la['TIME_POSITION'] = 'Время (позиция)';
    $la['DATE'] = 'Дата';
    $la['TIME'] = 'Время';
    $la['TODAY'] = 'Сегодня';
    $la['YESTERDAY'] = 'Вчера';
    $la['BEFORE_2_DAYS'] = '2 дня назад';
    $la['BEFORE_3_DAYS'] = '3 дня назад';
    $la['THIS_WEEK'] = 'На этой неделе';
    $la['LAST_WEEK'] = 'На прошедшей неделе';
    $la['THIS_MONTH'] = 'В этом месяце';
    $la['LAST_MONTH'] = 'В прошедшем месяце';
    $la['TIME_FROM'] = 'Время от';
    $la['TIME_TO'] = 'Время до';
    $la['PERIOD'] = 'Период';
    $la['DAILY'] = 'Ежедневный';
    $la['WEEKLY'] = 'Еженедельный';
    $la['MONTHLY'] = 'Ежемесячный';
    // date and time
    
    // location
    $la['LOCATION'] = "Дислокация";
    $la['POSITION'] = "Позиция";
    $la['ADDRESS'] = "Адрес";
    $la['ALTITUDE'] = "Высота";
    $la['ANGLE'] = "Угол";
    $la['SPEED'] = "Скорость";
    $la['COORDINATES'] = "Координаты";
    $la['LATITUDE'] = "Широта";
    $la['LONGITUDE'] = "Долгота";
    // location
    
    // events and alarms
    $la['NEW_EVENT'] = "Новое событие";
    $la['EVENTS'] = 'События';
    $la['EVENT'] = 'Событие';
    $la['SOUND_ALERT'] = 'Звуковой сигнал';
    $la['SOS'] = 'SOS';
    $la['BRACELET_ON'] = 'Браслет подключен';
    $la['BRACELET_OFF'] = 'Браслет отключен';
    $la['MAN_DOWN'] = 'Человек сбить с ног';
    $la['TOW'] = 'Буксир';
    $la['SHOCK'] = 'Шок';
    $la['OVERSPEED'] = 'Превышение скорости';
    $la['UNDERSPEED'] = 'Снижения скорости';
    $la['SUDDEN_ACCELERATION'] = 'Внезапное ускорение';
    $la['SUDDEN_BRAKING'] = 'Внезапное торможение';
    $la['POWER_CUT'] = 'Отключение питания';
    $la['LOW_BATTERY'] = 'Батарея разряжена';
    $la['NO_CONNECTION'] = 'Нет соединения';
    $la['SIGNAL_JAMMING'] = 'Глушение сигнала';
    $la['ZONE_IN'] = 'Прибытие';
    $la['ZONE_OUT'] = 'Отбытие';
    $la['SENSOR_CONDITION'] = 'Условие сенсора';
    $la['SELECTED_ZONES'] = 'Выбранные зоны';
    $la['EVENT_CONDITIONS'] = 'Условия события';
    $la['ENGINE_HOURS_REACHES'] = 'Моточасы достигают';
    $la['ODOMETER_REACHES'] = 'Пробег достигает';
    $la['MESSAGE_TO_EMAIL'] = 'Сообщение по эл. почте';
    $la['SMS_TO_MOBILE_PHONE'] = 'Отправлять SMS';
    $la['SYSTEM_MESSAGE'] = 'Сообщение от системы';
    $la['OBJECT_CONTROL'] = 'Управление объектом';
    $la['AUTO_HIDE'] = 'Авто. скрытие';
    $la['EVENT_PROPERTIES'] = 'Свойства события';
    $la['NO_CONNECTION_PERIOD'] = 'Нет соединения (мин)';
    $la['NOTIFICATION_ABOUT_EVENT'] = 'Извещение о событии';
    $la['THIS_IS_EVENT_MESSAGE'] = 'Это сообщение о событии, пожалуйста не отвечайте на данное сообщение.';
    $la['TRIGGER_EVENT'] = 'Инициировать события';
    // events and alarms
    
    // history and reports
    $la['HISTORY'] = 'История';
    $la['REPORTS'] = 'Отчеты';
    $la['REPORT'] = 'Отчет';
    $la['GRAPH'] = 'График';
    $la['MESSAGES'] = 'Сообщения';
    $la['STOPS'] = 'Остановки';
    $la['MOVING'] = 'В движении';
    $la['STOPPED'] = 'Стоит';
    $la['FILTER'] = 'Фильтр';
    $la['GENERAL_INFO'] = 'Общая информация';
    $la['GENERAL_INFO_MERGED'] = 'Общая информация (объединена)';
    $la['DRIVES_AND_STOPS'] = 'Движения и стоянки';
    $la['TRAVEL_SHEET'] = 'Поездки';
    $la['OVERSPEEDS'] = 'Превышения скорости';
    $la['UNDERSPEEDS'] = 'Снижения скорости';
    $la['ZONE_IN_OUT'] = 'Прибытия/выбытия в/из зоны';
    $la['FUEL_FILLINGS'] = 'Заправки топлива';
    $la['FUEL_THEFTS'] = 'Кражы топлива';
    $la['SCHEDULE'] = 'По расписанию';
    $la['LENGTH'] = 'Длина';
    $la['ROUTE_LENGTH'] = "Длина маршрута";
    $la['ROUTE_START'] = 'Начало маршрута';
    $la['ROUTE_END'] = 'Конец маршрута';
    $la['TOP_SPEED'] = 'Макс. скорость';
    $la['AVG_SPEED'] = 'Средняя скорость';
    $la['STOP_DURATION'] = 'Продолж. остановок';
    $la['MOVE_DURATION'] = 'Продолж. движения';
    $la['DURATION'] = 'Продолж.';
    $la['ENGINE_WORK'] = 'Работа двигателя';
    $la['ENGINE_IDLE'] = 'Холостой ход';
    $la['POSITION_A'] = 'Позиция A';
    $la['POSITION_B'] = 'Позиция B';
    $la['ZONE_POSITION'] = 'Позиция зоны';
    $la['STOP_POSITION'] = 'Позиция остановки';
    $la['EVENT_POSITION'] = 'Позиция события';
    $la['OVERSPEED_COUNT'] = 'Превышения скорости';
    $la['OVERSPEED_POSITION'] = 'Позиция превышения скорости';
    $la['UNDERSPEED_POSITION'] = 'Позиция снижения скорости';
    $la['SHOW_ADDRESSES'] = 'Показать адреса';
    $la['SPEED_LIMIT'] = 'Лимит скорости';
    $la['TIME_PERIOD'] = 'Период времени';
    $la['THIS_IS_REPORT_MESSAGE'] = 'Это отчетное сообщение, пожалуйста не отвечайте на данное сообщение.';
    $la['AFTER'] = 'После';
    $la['BEFORE'] = 'Перед';
    $la['STOLEN'] = 'Украдено';
    $la['FILLED'] = 'Заправнено';
    $la['CAME'] = "Прибыл";
    $la['LEFT'] = "Отбыл";
    $la['ARE_YOU_SURE_YOU_WANT_TO_CLEAR_HISTORY_EVENTS'] = "Вы уверены, что хотите удалить историю и события этого объекта?";
    // history and reports
    
    // account and personal
    $la['EXPIRING_OBJECTS'] = 'Истечения активации объектов';
    $la['SOME_OBJECTS_WILL_EXPIRE_SOON'] = 'Срок активации некоторых ваших объектов скоро истечёт.';
    $la['PLEASE_LOGIN_INTO_ACCOUNT_FOR_MORE_DETAILS'] = 'Пожалуйста, войдите в аккаунт для более подробной информации.';
    $la['PLEASE_PURCHASE_ACCESS_TO'] = 'Если вы хотели бы продолжить использование нашего сервиса, пожалуйста, приобрести доступ к';
    $la['AT_OUR_SHOP'] = 'в нашем магазине:';
    $la['REGISTRATION'] = 'Регистрация';
    $la['LOGIN_DATA_WILL_BE_SENT_TO_EMAIL'] = 'Данные будут отправлены по указанному адресу.';
    $la['REGISTRATION_SUCCESSFUL'] = 'Вы успешно зарегистрировались.';
    $la['THANK_YOU_FOR_REGISTERING_AT'] = "Благодарим за регистрацию в {$gsValues['NAME']}.";
    $la['THIS_EMAIL_ALREADY_EXISTS'] = 'Такая эл. почта уже существует.';
    $la['USERNAME_PASSWORD_SENT'] = 'Имя пользователя и пароль отправлены.';
    $la['REGISTRATION_AT'] = "Регистрация в {$gsValues['NAME']}";
    $la['ACCESS_TO_GPS_SERVER_ACCOUNT'] = 'Доступ к GPS серверу';
    $la['LOST_LOGIN_RECOVERY'] = 'Забыли пароль?';
    $la['ENTER_USERNAME_AND_PASSWORD_TO_LOGIN'] = 'Введите имя пользователя и пароль для входа.';
    $la['NEW_LOGIN_DATA_WILL_BE_SENT_TO_EMAIL'] = 'Новый пароль будет отправлен по указанному адресу.';
    $la['THIS_EMAIL_IS_NOT_REGISTERED'] = 'Данный адрес эл. почты незарегистрирован.';
    $la['LOST_LOGIN_RECOVERY_TO'] = "Восстановление утерянного логина на {$gsValues['NAME']}";
    $la['YOUR_ACCOUNT_IS_LOCKED'] = "Ваш аккаунт заблокирован. Свяжитесь, пожалуйста, с нами по {$gsValues['EMAIL']}.";
    $la['USERNAME_OR_PASSWORD_INCORRECT'] = 'Неправильное имя пользователя или пароль.';
    $la['PLEASE_CHECK_YOUR_EMAIL'] = 'Проверьте, пожалуйста, свою эл. почту.';
    $la['EMAIL'] = 'Эл. почта';
    $la['USERNAME'] = 'Пользователь';
    $la['PASSWORD'] = 'Пароль';
    $la['SETTINGS'] = 'Настройки';
    $la['USER'] = 'Пользователь';
    $la['PRIVILEGES'] = "Права";
    $la['PHONE'] = 'Телефон';
    $la['COMPANY'] = 'Компания';
    $la['CITY'] = 'Город';
    $la['CONTACT_INFO'] = 'Контактные данные';
    $la['NAME_SURNAME'] = 'Имя, фамилия';
    $la['POST_CODE'] = 'Почтовый индекс';
    $la['COUNTRY_STATE'] = 'Страна/Штат';
    $la['PHONE_NUMBER_1'] = 'Номер тел. 1';
    $la['PHONE_NUMBER_2'] = 'Номер тел. 2';
    $la['CHANGE_PASSWORD'] = "Сменить пароль";
    $la['OLD_PASSWORD'] = "Старый пароль";
    $la['NEW_PASSWORD'] = "Новый пароль";
    $la['REPEAT_NEW_PASSWORD'] = "Повторите новый пароль";
    $la['MY_ACCOUNT'] = 'Мой аккаунт';
    $la['SUB_ACCOUNTS'] = 'Субаккаунты';
    $la['SUB_ACCOUNT'] = 'Субаккаунт';
    $la['EMAIL_ADDRESS'] = 'Адрес эл. почты';
    $la['PHONE_NUMBER_WITH_CODE'] = 'Номер телефона с кодом';
    $la['REMEMBER_ME'] = 'Запомнить меня';
    $la['SELECTED_OBJECTS'] = 'Выбранные объекты';
    $la['SUB_ACCOUNT_PROPERTIES'] = 'Свойства субаккаунта';
    $la['SUB_ACCOUNTS_CAN_SPLIT_THIS_ACCOUNT_INTO_MULTIPLE_SMALLER_ACCOUNTS'] = 'Субаккаунты могут разделить этот аккаунт на несколько более мелких аккаунтов с ограниченными правами.';
    $la['CONTACT_ADMIN_IF_YOU_WANT_TO_DO_ANY_CHANGES'] = 'Свяжитесь с администратором, если хотите сделать какие-либо изменения с объектами.';
    $la['NEWLY_ADDED_GPS_OBJECTS_CAN_BE_USED_FOR'] = "Новые добавленные GPS объекты могут быть использованы в течение {$gsValues['OBJ_TRIAL_PERIOD']} дней бесплатно.";
    $la['YOU_CAN_ADD'] = 'Вы можете добавить';
    $la['GPS_OBJECTS_TILL'] = 'GPS объект(ы) до';
    $la['EXPAND_THIS_LIMIT_IN_OUR_SHOP'] = "Ллимит можете увеличить в <a href='{$gsValues['URL_SHOP']}' target='_blank'>магазине</a>.";
    $la['YOU_CAN_ADD_UNLIMITED_NUMBER_OF_GPS_OBJECTS_TILL'] = 'Вы можете добавить неограниченное количество GPS объектов до';
    $la['YOUR_SESSION_HAS_EXPIRED'] = "Ваша сессия истекла. <a href='{$gsValues['URL_LOGIN']}'>Войдите</a>, пожалуйста, снова.";
    $la['SMS'] = "SMS";
    $la['SMS_GATEWAY'] = "SMS шлюз";
    $la['ENABLE_SMS_GATEWAY'] = 'Включить SMS шлюз';
    $la['SMS_GATEWAY_URL'] = 'URL SMS шлюза';
    $la['SMS_GATEWAY_EXPLANATION'] = 'Следует использовать SMS шлюз, которые могут отправлять сообщения через HTTP GET.';
    $la['SMS_GATEWAY_VARIABLES'] = 'Переменные: %NUMBER%, %MESSAGE%.';
    $la['SMS_GATEWAY_EXAMPLE'] = 'Пример URL SMS шлюза: http://SMS_GATEWAY/sendsms.php?username=USER&password=PASSWORD&number=%NUMBER%&message=%MESSAGE%';
    // account and personal
    
    // object
    $la['ALL_OBJECTS'] = 'Все объекты';
    $la['SEND_COMMAND'] = 'Отправить команду';
    $la['OBJECT_LIST'] = 'Список объектов';
    $la['OBJECT'] = 'Объект';
    $la['OBJECTS'] = 'Объекты';
    $la['IMEI'] = 'IMEI';
    $la['COMMAND'] = 'Команда';
    $la['COMMANDS'] = 'Команды';
    $la['COMMANDS_STATUS'] = 'Статус команд';
    $la['COMMAND_PROPERTIES'] = 'Свойства команды';
    $la['GATEWAY'] = 'Шлюз';
    $la['GROUP'] = 'Группа';
    $la['DRIVER'] = 'Водитель';
    $la['ODOMETER'] = 'Одометр';
    $la['ABSOLUTE_ODOMETER'] = 'Абсолютный одометр';
    $la['RELATIVE_ODOMETER'] = 'Относительный одометр';
    $la['ABSOLUTE_ENGINE_HOURS'] = 'Абсолютные моточасы';
    $la['RELATIVE_ENGINE_HOURS'] = 'Относительные моточасы';
    $la['SUMMER_RATE'] = 'Летом';
    $la['WINTER_RATE'] = 'Зимой';
    $la['WINTER_FROM'] = 'Зима от (месяц, число)';
    $la['WINTER_TO'] = 'Зима до (месяц, число)';
    $la['TRANSPORT_MODEL'] = 'Модель транспортного средства';
    $la['PLATE_NUMBER'] = 'Номерной знак';
    $la['SIM_CARD_NUMBER'] = '№ SIM-карты';
    $la['ENGINE_HOURS'] = 'Моточасы';
    $la['GPS_DEVICE'] = 'GPS устройство';
    $la['FUEL_CONSUMPTION'] = 'Расход топлива';
    $la['AVAILABLE_OBJECTS'] = 'Доступные объекты';
    $la['SENSOR'] = 'Сенсор';
    $la['SENSORS'] = 'Сенсоры';
    $la['SENSOR_PROPERTIES'] = 'Свойства сенсора';
    $la['CALIBRATION'] = 'Калибрование';
    $la['IGNITION_ACC'] = 'Зажигание (ACC)';
    $la['DIGITAL_INPUT'] = 'Цифровой вход';
    $la['DIGITAL_OUTPUT'] = 'Цифровой выход';
    $la['FUEL_LEVEL'] = 'Уровень топлива';
    $la['PARAMETER'] = 'Параметр';
    $la['UNITS_OF_MEASUREMENT'] = 'Единицы измерения';
    $la['IF_SENSOR_1'] = 'Сенсор "1", (текст)';
    $la['IF_SENSOR_0'] = 'Сенсор "0", (текст)';
    $la['LOWEST_VALUE'] = 'Мин. значение';
    $la['HIGHEST_VALUE'] = 'Макс. значение';
    $la['FORMULA'] = 'Формула';
    $la['ACCURACY'] = 'Точность';
    $la['DETECT_STOPS_USING'] = 'Обнаружение остановок используя';
    $la['MIN_MOVING_SPEED'] = 'Мин. скорость движения в km/h (влияет на остановки и точность трека, рек. 6)';
    $la['MIN_DIFF_BETWEEN_POINTS'] = 'Мин. разница между координатами (устраняет дрейф, рек. 0.0005)';
    $la['MIN_GPSLEV_VALUE'] = 'Мин. gpslev значение (устраняет дрейф, рек. 5)';
    $la['MAX_HDOP_VALUE'] = 'Макс. hdop значение (устраняет дрейф, рек. 3)';
    $la['MIN_FF'] = "Мин. разница топлива для обнаружения заправок (рек. 10)";
    $la['MIN_FT'] = "Мин. разница топлива для обнаружения топливных краж (рек. 10)";
    $la['SERVICE'] = 'Обслуживание';
    $la['SERVICE_PROPERTIES'] = 'Свойства обслуживания';
    $la['ODOMETER_INTERVAL'] = 'Интервал пробега';
    $la['ENGINE_HOURS_INTERVAL'] = 'Интервал моточасов';
    $la['DAYS_INTERVAL'] = 'Интервал дней';
    $la['LAST_SERVICE'] = 'Последнее обслуживание';
    $la['UPDATE_LAST_SERVICE'] = 'Обновить последнее обслуживание';
    $la['CURRENT_OBJECT_COUNTERS'] = 'Текущие счетчики объекта';
    $la['CURRENT_ODOMETER'] = 'Текущий одометр';
    $la['CURRENT_ENGINE_HOURS'] = 'Текущие моточасы';
    $la['OBJECT_DRIVER_LIST'] = 'Водитель объектов';
    $la['OBJECT_DRIVER_PROPERTIES'] = 'Свойства водитель объектов';
    $la['OBJECT_GROUP_LIST'] = 'Группы объектов';
    $la['OBJECT_GROUP_PROPERTIES'] = 'Свойства группы объектов';
    $la['FIT_OBJECTS_ON_MAP'] = 'Вместит объекты на карте';
    $la['NO_OBJECTS'] = 'Нет объектов';
    $la['LOGIC'] = 'Логицеский';
    $la['STRING'] = 'Строка';
    $la['PERCENTAGE'] = 'Процент';
    $la['PARAMETERS'] = "Параметры";
    $la['MODEL'] = "Модель";
    $la['PLATE'] = "Номер";
    $la['NO_DRIVER'] = "Нет водитель";
    $la['ACTIVE_TILL'] = 'Активен до';
    $la['DRIVER_INFO'] = "Информирования о водителе";  
    $la['CHECK_GPS_SIGNAL'] = 'Проверьте GPS сигнал';
    $la['NO_DATA'] = "Нет данных";
    $la['NO_DATA_HAS_BEEN_RECEIVED_YET'] = "Еще не было получено данных от GPS устройства.";
    $la['SENSOR_PARAMETERS_ARE_NOT_DETECTED_FOR_THIS_GPS_DEVICE'] = "Сенсоры для этого GPS устройства еще не обнаружены.";
    $la['AT_LEAST_ONE_OBJECT_SELECTED'] = 'Должен быть выбран хотя бы один объект.';
    $la['COMMAND_SENT_FOR_EXECUTION'] = "Команда успешно отправить на выполнение.";
    $la['INACTIVE_OBJECTS'] = "Неактивные объекты";
    $la['THERE_ARE_INACTIVE_OBJECTS_IN_YOUR_ACCOUNT'] = 'В вашем аккаунте имеются неактивные объекты. Перейдите в раздел <a href="#" onclick="settingsOpen();">настройки</a> для более подробной информации.';
    $la['EXPIRING_OBJECTS'] = "Истечения активации объектов";
    $la['SOME_OF_YOUR_OBJECTS_ACTIVATION_WILL_EXPIRE_SOON'] = 'Срок активации некоторых ваших объектов скоро истечёт. Перейдите в раздел <a href="#" onclick="settingsOpen();">настройки</a> для более подробной информации.';
    // object
    
    // places
    $la['ADD_ZONE'] = 'Добавить зону';
    $la['ADD_MARKER'] = 'Добавить маркер';
    $la['NEW_ZONE'] = 'Новая зона';
    $la['NEW_MARKER'] = 'Новый маркер';  
    $la['NEAREST_ZONE'] = "Ближайшая зона";
    $la['NEAREST_MARKER'] = "Ближайший маркер";
    $la['AT_LEAST_ONE_ZONE_SELECTED'] = 'Должна быть выбрана хотя бы одна зона.';
    $la['DRAW_ZONE_ON_MAP_BEFORE_SAVING'] = "Перед сохранением начертите зону на карте.";
    $la['PLACE_MARKER_ON_MAP_BEFORE_SAVING'] = "Перед сохранением установите на карте маркер.";
    $la['PLACES'] = 'Места';
    $la['ZONES'] = 'Зоны';
    $la['MARKERS'] = 'Маркеры';
    $la['ZONE_NAME'] = 'Название';
    $la['MARKER_PROPERTIES'] = 'Свойства маркера';
    $la['MARKER_VISIBLE'] = 'Маркер видим';
    $la['ZONE_PROPERTIES'] = 'Свойства зоны';
    $la['ZONE_VISIBLE'] = 'Зона видима';
    $la['NAME_VISIBLE'] = 'Название видимо';
    $la['AVAILABLE_ZONES'] = 'Доступные зоны';
    $la['AVAILABLE_MARKERS'] = 'Доступные маркера';
    // places
    
    // settings
    $la['CHANGES_SAVED_SUCCESSFULLY'] = 'Параметры успешно сохранены.';
    $la['SETTINGS_NOT_SAVED'] = 'Установочные параметры не сохранились.';
    $la['PASSWORD_CANT_BE_EMPTY'] = "Введите пароль.";
    $la['INCORRECT_PASSWORD'] = "Неправильный пароль.";
    $la['REPEATED_PASSWORD_IS_INCORRECT'] = "Повторный пароль неправильный.";
    $la['PASSWORD_LENGHT_AT_LEAST'] = "Пароль должен включать не менее 6 симфолов.";
    $la['TIMEZONE'] = 'Временная зона';    
    $la['REMEMBER_MAP_POSITION'] = 'Запомнить последнюю позицию карты';
    $la['SHOW_OBJECT_TAIL'] = 'Показывать хвост объекта';
    $la['OBJECT_TAIL_COLOR'] = 'Цвет хвоста объекта';
    $la['HISTORY_ROUTE_COLOR'] = 'Цвет истории маршрута';
    $la['HISTORY_ROUTE_HIGHLIGHT_COLOR'] = 'Выделенный цвет истории маршрута';
    $la['SHOWN_ICON_ON_MAP'] = 'Иконка на карте';
    $la['ADD_OBJECT'] = 'Добавить объект';
    $la['EDIT_OBJECT'] = 'Свойства объекта';
    $la['DUPLICATE_OBJECT'] = 'Дублировать объект';
    $la['SELECT_ICON'] = 'Выберите иконку';
    $la['USER_INTERFACE'] = 'Интерфейс';
    // settings
    
    // other
    $la['LOADING'] = 'Загрузка...';
    $la['ADD'] = 'Добавить';
    $la['SYSTEM'] = 'Система';
    $la['DATA'] = "Данные";
    $la['VALUE'] = "Значение";
    $la['GENERAL'] = "Общий";
    $la['INFORMATION'] = "Информация";
    $la['ERROR'] = "Ошибка";
    $la['ID_NUMBER'] = "ID код";
    $la['CREATE'] = 'Создать';
    $la['HELLO'] = 'Здравствуйте';
    $la['CUSTOM'] = 'Собственный';
    $la['MAIN'] = 'Главные';
    $la['NAME'] = 'Название';
    $la['COLOR'] = 'Цвет';
    $la['ICON'] = 'Иконка';
    $la['TYPE'] = 'Тип';
    $la['RESULT'] = 'Результат';
    $la['ABOUT'] = 'О системе';
    $la['HELP'] = 'Помощь';
    $la['RULER'] = 'Линейка';
    $la['DESCRIPTION'] = 'Описание';
    $la['FORMAT'] = 'Формат';
    $la['UNGROUPED'] = 'Разгрупированы';
    $la['PER'] = 'на';
    $la['ACTIVATE'] = 'Активировать';
    $la['ACTIVE'] = "Активный";
    $la['ARROW'] = 'Стрелка';
    $la['OTHER'] = 'Другое';
    $la['STATUS'] = 'Статус';
    $la['TOTAL'] = 'Сумма';
    $la['START'] = 'Начало';
    $la['END'] = 'Конец';
    $la['SEND_TO_EMAIL'] = 'Отправить по эл. почте';
    $la['ENTER_CODE'] = 'Введите код';
    $la['SHOW_POINT'] = 'Показать пункт';
    $la['ADDRESS_SEARCH'] = 'Поиск адреса';
    $la['CANT_SEND_EMAIL'] = "Письмо не отправляются.";
    $la['CONTACT_ADMINISTRATOR'] = "Свяжитесь с администратором.";
    $la['NOTHING_HAS_BEEN_FOUND_ON_YOUR_REQUEST'] = 'По вашему запросу ничего не найдено.';
    $la['HOLD_CTRL_TO_SELECT_MULTIPLE_ITEMS'] = 'Для выбора нескольких пунктов нажмите и держите клавишу "Ctrl"';
    $la['SECURITY_CODE_IS_INCORRECT'] = 'Неправильный защитный код.';
    $la['ODOMETER_LEFT'] = 'Одометр осталос';
    $la['ODOMETER_EXPIRED'] = 'Одометр истек';
    $la['ENGINE_HOURS_LEFT'] = 'Моточасов осталос';
    $la['ENGINE_HOURS_EXPIRED'] = 'Моточасы истекли';
    $la['DAYS_LEFT'] = 'Дней осталось';
    $la['DAYS_EXPIRED'] = 'Дни истекли';
    // other
    
    // invalid messages
    $la['INTERVAL_VALUE_SHOULD_BE_GREATER_THAN_LEFT_VALUE'] = "Значение 'интервал' должно быть больше, чем 'осталос' значение.";
    $la['THERE_IS_NO_SUCH_OBJECT_IN_YOUR_ACCOUNT'] = "Нет такого объекта в вашем аккаунте."; 
    $la['INVALID_FILE_FORMAT'] = "Данный формат файла не поддерживается.";    
    $la['THIS_EMAIL_IS_NOT_VALID'] = 'Электронная почта является неправильной.';
    $la['COMMAND_HEX_NOT_VALID'] = "Формат команды HEX является неправильным.";
    $la['NAME_CANT_BE_EMPTY'] = "Введите название.";
    $la['THIS_IMEI_IS_NOT_VALID'] = "IMEI является неправильным.";
    $la['COMMAND_CANT_BE_EMPTY'] = "Введите команду.";
    $la['SPEED_LIMIT_CANT_BE_EMPTY'] = "Введите лимит скорости.";
    $la['ALL_AVAILABLE_FIELDS_SHOULD_BE_FILLED_OUT'] = "Все возможные поля должны быть заполнены.";
    $la['THIS_IMEI_ALREADY_EXISTS'] = "Данный IMEI уже существует.";
    $la['YOU_HAVE_REACHED_THE_LIMIT_OF_OBJECTS'] = 'У вас имеется максимальное количество объектов.';
    $la['THIS_ACCOUNT_HAS_NO_PRIVILEGES_TO_DO_THAT'] = "Совершение каких-либо изменений не допускается.";
    $la['NOTHING_HAS_BEEN_FOUND'] = "По вашему запросу ничего не найдено.";
    $la['NOTHING_HAS_BEEN_FOUND_TO_IMPORT'] = "Ничего не было найдено для импорта.";
    $la['IMPORT_FILE_IS_TOO_BIG'] = "Импорт файл слишком большой.";
    $la['IGNITION_SENSOR_IS_ALREADY_AVAILABLE'] = "Датчик зажигания уже имеется.";
    $la['AT_LEAST_TWO_CALIBRATION_POINTS'] = "Как минимум два калибровочных пункта должны быть использованы.";
    $la['SAME_X_CALIBRATION_CHECK_POINT_AVAILABLE'] = "Тот же самый X калибровочный пункт уже имеется.";
    // invalid messages
    
    // questions
    $la['ARE_YOU_SURE_YOU_WANT_TO_OVERWRITE_SELECTED_COMMAND'] = "Вы уверены, что хотите перезаписать выбранную команду?";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE_ALL_EVENTS'] = "Вы уверены, что хотите удалить все события?";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE_ALL_PLACES'] = "Вы уверены, что хотите удалить все места?";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE'] = "Вы уверены, что хотите удалить";
    $la['ZONES_FOUND'] = 'зоны найдено.';
    $la['MARKERS_FOUND'] = 'маркеров найдено.';
    $la['ARE_YOU_SURE_YOU_WANT_TO_IMPORT'] = "Вы уверены, что хотите импортировать?";
    // questions
?>