<?
    // software
    $la['COPYRIGHT'] = "{$gsValues['NAME']} {$gsValues['VERSION']} &copy <a href='{$gsValues['URL_CONTACT']}' target='_blank'>{$gsValues['NAME']}</a>, 2010-2016. All rights reserved.";
    $la['CONNECT_TO'] = "ربط{$gsValues['NAME']}";
    $la['LANGUAGE'] = 'لغة';
    $la['MAP'] = 'خريطة';
    $la['MOBILE_VERSION'] = 'الهاتف المحمول';
    $la['DESKTOP_VERSION'] = 'نسخة الكمبيوتر';
    $la['PLEASE_WAIT'] = 'يرجى الانتظار';
    // software
    
    // calendar
    $la['DAY_SUNDAY_S'] = "S";
    $la['DAY_MONDAY_S'] = "M";
    $la['DAY_TUESDAY_S'] = "T";
    $la['DAY_WEDNESDAY_S'] = "W";
    $la['DAY_THURSDAY_S'] = "T";
    $la['DAY_FRIDAY_S'] = "F";
    $la['DAY_SATURDAY_S'] = "S";
    $la['MONTH_JANUARY'] = "يناير";
    $la['MONTH_FEBRUARY'] = "فبراير";
    $la['MONTH_MARCH'] = "مارس";
    $la['MONTH_APRIL'] = "أبريل";
    $la['MONTH_MAY'] = "مايو";
    $la['MONTH_JUNE'] = "يونيو";
    $la['MONTH_JULY'] = "يوليو";
    $la['MONTH_AUGUST'] = "أغسطس";
    $la['MONTH_SEPTEMBER'] = "سبتمبر";
    $la['MONTH_OCTOBER'] = "أكتوبر";
    $la['MONTH_NOVEMBER'] = "نوفمبر";
    $la['MONTH_DECEMBER'] = "ديسمبر";
    // calendar
    
    // units
    $la['UNIT_KPH'] = 'كيلومترات في الساعة';
    $la['UNIT_KM'] = 'كيلومترا';
    $la['UNIT_M'] = 'متر';
    $la['UNIT_MPH'] = 'ميلا في الساعة';
    $la['UNIT_MI'] = 'ميل';
    $la['UNIT_FT'] = 'قدم';
    $la['UNIT_GALLONS'] = 'غالون';
    $la['UNIT_LITERS'] = 'لتر';
    $la['UNIT_D'] = 'يوم';
    $la['UNIT_H'] = 'ساعة';
    $la['UNIT_MIN'] = 'دقيقة';
    $la['UNIT_S'] = 'ثانية';
    $la['UNIT_OF_DISTANCE'] = 'وحدة  مسافة';
    $la['UNIT_OF_CAPACITY'] = 'وحدة  قدرة';
    $la['UNIT_OF_TEMPERATURE'] = 'درجة الحرارة';
    $la['MILE'] = 'ميل';
    $la['KILOMETER'] = 'كيلومتر';
    $la['LITER'] = 'لتر';
    $la['GALLON'] = 'غالون';
    $la['CELSIUS'] = 'سلسيوس';
    $la['FAHRENHEIT'] = 'درجة الحرارة';
    // units
    
    // buttons
    $la['SET'] = 'ضبط';
    $la['RELOAD'] = 'تحديث ';
    $la['DELETE_ALL_EVENTS'] = 'حذف جميع الأحداث';
    $la['DELETE_ALL_PLACES'] = 'حذف جميع الأماكن';
    $la['IMPORT'] = 'استيراد';
    $la['EXPORT'] = 'تصدير';
    $la['PLAY'] = 'لعب';
    $la['PAUSE'] = 'وقفة';
    $la['STOP'] = 'توقف';
    $la['PAN_LEFT'] = ' اليسار';
    $la['PAN_RIGHT'] = 'اليمين';
    $la['ZOOM_IN'] = 'تكبير';
    $la['ZOOM_OUT'] = 'تصغير';
    $la['MENU'] = 'قائمة';
    $la['RECOVER'] = 'ذكر';
    $la['YES'] = 'نعم';
    $la['NO'] = 'لا';
    $la['SEARCH'] = 'بحث';
    $la['SHOW'] = 'عرض';
    $la['HIDE'] = 'إخفاء';
    $la['NEW'] = 'جديد';
    $la['SAVE'] = 'حفظ';
    $la['SEND'] = 'إرسال';
    $la['CANCEL'] = 'إلغاء';
    $la['DEFAULT'] = 'الافتراضي';
    $la['EDIT'] = 'تحرير';
    $la['DELETE'] = 'حذف';
    $la['LOGOUT'] = 'تسجيل الخروج';
    $la['LOGIN'] = 'دخول';
    $la['REGISTER'] = 'تسجيل';
    $la['LOAD_GSR'] = 'تحميل GSR';
    $la['EXPORT_GSR'] = 'التصدير إلى GSR';
    $la['EXPORT_KML'] = 'التصدير إلى KML';
    $la['EXPORT_GPX'] = 'التصدير إلى GPX';
    $la['CREATE_NOW'] = 'إنشاء الآن';
    $la['SHOW_HISTORY'] = 'إظهار التاريخ';
    $la['DUPLICATE'] = 'تكرار';
    $la['CLEAR_HISTORY'] = 'حذف السجلات';
    // buttons
    
    // date and time
    $la['DATE'] = 'تاريخ';
    $la['TIME'] = 'وقت';
    $la['TODAY'] = 'اليوم';
    $la['YESTERDAY'] = 'أمس';
    $la['BEFORE_2_DAYS'] = 'قبل  2أيام ';
    $la['BEFORE_3_DAYS'] = 'قبل 3 أيام';
    $la['THIS_WEEK'] = 'هذا الاسبوع';
    $la['LAST_WEEK'] = 'الأسبوع الماضي';
    $la['THIS_MONTH'] = 'هذا الشهر';
    $la['LAST_MONTH'] = 'الشهر الماضي';
    $la['TIME_FROM'] = 'الوقت من';
    $la['TIME_TO'] = 'الوقت الى';
    $la['PERIOD'] = 'فترة';
    $la['DAILY'] = 'يوميا';
    $la['WEEKLY'] = 'الأسبوعية';
    $la['MONTHLY'] = 'شهريا';
    // date and time
    
    // location
    $la['LOCATION'] = "موقع";
    $la['POSITION'] = "موقف";
    $la['ADDRESS'] = "عنوان";
    $la['ALTITUDE'] = "ارتفاع";
    $la['ANGLE'] = "زاوية";
    $la['SPEED'] = "السرعة";
    $la['COORDINATES'] = "الإحداثيات";
    $la['LATITUDE'] = "خط العرض";
    $la['LONGITUDE'] = "خط الطول";
    // location
    
    // events and alarms
    $la['NEW_EVENT'] = "الحدث الجديد";
    $la['EVENTS'] = 'أحداث';
    $la['EVENT'] = 'حدث';
    $la['SOUND_ALERT'] = 'تنبيه الصوت';
    $la['SOS'] = 'نجدة';
    $la['BRACELET_ON'] = 'تشغيل  سوار';
    $la['BRACELET_OFF'] = 'اقفال  سوار ';
    $la['MAN_DOWN'] = 'هبوط';
    $la['TOW'] = 'سحب';
    $la['SHOCK'] = 'صدمة';
    $la['OVERSPEED'] = 'السرعة الزائدة';
    $la['UNDERSPEED'] = 'تحت سرعة';
    $la['SUDDEN_ACCELERATION'] = 'التسارع المفاجئ';
    $la['SUDDEN_BRAKING'] = 'الكبح المفاجئ';
    $la['POWER_CUT'] = 'إنقطاع التيار الكهربائي';
    $la['LOW_BATTERY'] = 'البطارية منخفضة';
    $la['NO_CONNECTION'] = 'ربط غير متاح';
    $la['SIGNAL_JAMMING'] = 'التشويش إشارة';
    $la['ZONE_IN'] = 'داخل المنطقة';
    $la['ZONE_OUT'] = 'خارج المنطقة';
    $la['SENSOR_CONDITION'] = 'حالة استشعار';
    $la['SELECTED_ZONES'] = 'مناطق مختارة';
    $la['EVENT_CONDITIONS'] = 'ظروف الحدث';
    $la['ENGINE_HOURS_REACHES'] = 'ساعات المحرك ';
    $la['ODOMETER_REACHES'] = 'عداد المسافات';
    $la['MESSAGE_TO_EMAIL'] = 'رسالة إلى البريد الإلكتروني';
    $la['SMS_TO_MOBILE_PHONE'] = 'SMS الهاتف المحمول';
    $la['SYSTEM_MESSAGE'] = 'رسالة النظام';
    $la['OBJECT_CONTROL'] = 'مراقبة العربة';
    $la['AUTO_HIDE'] = 'إخفاء تلقائي';
    $la['EVENT_PROPERTIES'] = 'خصائص الحدث';
    $la['NO_CONNECTION_PERIOD'] = '(لا اتصال الفترة (دقيقة ';
    $la['NOTIFICATION_ABOUT_EVENT'] = 'إعلام حول الحدث';
    $la['THIS_IS_EVENT_MESSAGE'] = 'هذا هو رسالة الحدث، يرجى عدم الرد على هذه الرسالة.';
    $la['TRIGGER_EVENT'] = 'اثار الحدث';
    // events and alarms
    
    // history and reports
    $la['HISTORY'] = 'تاريخ';
    $la['REPORTS'] = 'تقارير';
    $la['REPORT'] = 'تقرير';
    $la['GRAPH'] = 'رسم بياني';
    $la['MESSAGES'] = 'رسائل';
    $la['STOPS'] = 'توقف';
    $la['MOVING'] = 'متحرك';
    $la['STOPPED'] = 'توقف';
    $la['FILTER'] = 'اختيار';
    $la['GENERAL_INFO'] = 'معلومات عامة';
    $la['GENERAL_INFO_MERGED'] = ' (معلومات عامة (المدمجة ';
    $la['DRIVES_AND_STOPS'] = 'تحرك و توقف';
    $la['TRAVEL_SHEET'] = 'ورقة السفر';
    $la['OVERSPEEDS'] = 'السرعة الزائدة';
    $la['UNDERSPEEDS'] = 'تحت سرعة';
    $la['ZONE_IN_OUT'] = 'منطقة داخل / خارج';
    $la['FUEL_FILLINGS'] = 'حشو الوقود';
    $la['FUEL_THEFTS'] = 'سرقة الوقود';
    $la['SCHEDULE'] = 'جدول';
    $la['LENGTH'] = 'طول';
    $la['ROUTE_LENGTH'] = "طول الطريق";
    $la['ROUTE_START'] = 'بداية الطريق';
    $la['ROUTE_END'] = 'نهاية الطريق';
    $la['TOP_SPEED'] = 'السرعة القصوى';
    $la['AVG_SPEED'] = 'متوسط ​​السرعة';
    $la['STOP_DURATION'] = 'مدة التوقف';
    $la['MOVE_DURATION'] = 'مدة التحرك';
    $la['DURATION'] = 'مدة';
    $la['ENGINE_WORK'] = 'عمل محرك';
    $la['ENGINE_IDLE'] = 'محرك راكد';
    $la['POSITION_A'] = 'موقف A';
    $la['POSITION_B'] = 'موقف B';
    $la['ZONE_POSITION'] = 'موقف المنطقة';
    $la['STOP_POSITION'] = 'مكان التوقف';
    $la['EVENT_POSITION'] = 'موقف الحدث';
    $la['OVERSPEED_COUNT'] = 'عد السرعة الزائدة';
    $la['OVERSPEED_POSITION'] = 'موقف السرعة الزائدة';
    $la['UNDERSPEED_POSITION'] = ' موقف السرعة الدنوى ';
    $la['SHOW_ADDRESSES'] = 'اظهارالعنوان';
    $la['SPEED_LIMIT'] = 'حد السرعة';
    $la['TIME_PERIOD'] = 'حد السرعة';
    $la['THIS_IS_REPORT_MESSAGE'] = 'هذا هو رسالة التقرير، يرجى عدم الرد على هذه الرسالة.';
    $la['AFTER'] = 'بعد';
    $la['BEFORE'] = 'قبل';
    $la['STOLEN'] = 'مسروق';
    $la['FILLED'] = 'معبأ';
    $la['CAME'] = "Came";
    $la['LEFT'] = "اليسار";
    $la['ARE_YOU_SURE_YOU_WANT_TO_CLEAR_HISTORY_EVENTS'] = "هل أنت متأكد من أنك تريد مسح هذا التاريخ والأحداث ؟";
    // history and reports
    
    // account and personal
    $la['EXPIRING_OBJECTS'] = 'انتهاء التفعيل';
    $la['SOME_OBJECTS_WILL_EXPIRE_SOON'] = 'بعض عرباتك ستنتهي مدة تفعيلها قريبا ';
    $la['PLEASE_LOGIN_INTO_ACCOUNT_FOR_MORE_DETAILS'] = 'يرجى الدخول إلى حسابك للحصول على مزيد من التفاصيل.';
    $la['PLEASE_PURCHASE_ACCESS_TO'] = 'إذا كنت ترغب في الاستمرار في استخدام الخدمة التي نقدمها، يرجى شراء الحصول على';
    $la['AT_OUR_SHOP'] = 'في متجر لدينا:';
    $la['REGISTRATION'] = 'تسجيل';
    $la['LOGIN_DATA_WILL_BE_SENT_TO_EMAIL'] = 'سيتم إرسال بيانات تسجيل الدخول إلى  عنوان البريد الإلكتروني.';
    $la['REGISTRATION_SUCCESSFUL'] = 'نجاح عملية التسجيل.';
    $la['THANK_YOU_FOR_REGISTERING_AT'] = "شكرا لك على التسجيل في {$gsValues['NAME']}.";
    $la['THIS_EMAIL_ALREADY_EXISTS'] = 'هذا البريد الإلكتروني موجود بالفعل.';
    $la['USERNAME_PASSWORD_SENT'] = 'اسم المستخدم وكلمة المرور المرسلة.';
    $la['REGISTRATION_AT'] = "التسجيل في {$gsValues['NAME']}";
    $la['ACCESS_TO_GPS_SERVER_ACCOUNT'] = ' GPS server الوصول إلى';
    $la['LOST_LOGIN_RECOVERY'] = 'اعادة الربط';
    $la['ENTER_USERNAME_AND_PASSWORD_TO_LOGIN'] = 'أدخل البريد الإلكتروني وكلمة المرور لتسجيل الدخول.';
    $la['NEW_LOGIN_DATA_WILL_BE_SENT_TO_EMAIL'] = 'سيتم إرسال بيانات تسجيل الدخول الجديدة إلى إعطاء  البريد الإلكتروني.';
    $la['THIS_EMAIL_IS_NOT_REGISTERED'] = 'لم يتم تسجيل عنوان البريد الإلكتروني.';
    $la['LOST_LOGIN_RECOVERY_TO'] = "اعادة الربط {$gsValues['NAME']}";
    $la['YOUR_ACCOUNT_IS_LOCKED'] = "تم تأمين حسابك. يرجى الاتصال بنا عبر {$gsValues['EMAIL']}.";
    $la['USERNAME_OR_PASSWORD_INCORRECT'] = 'اسم المستخدم أو كلمة المرور غير صحيحة.';
    $la['PLEASE_CHECK_YOUR_EMAIL'] = 'يرجى التحقق من البريد الإلكتروني الخاص بك.';
    $la['EMAIL'] = 'البريد الإلكتروني';
    $la['USERNAME'] = 'اسم المستخدم';
    $la['PASSWORD'] = 'كلمة السر';
    $la['SETTINGS'] = 'إعدادات';
    $la['USER'] = 'المستخدم';
    $la['PRIVILEGES'] = "امتيازات";
    $la['PHONE'] = 'هاتف';
    $la['COMPANY'] = 'شركة';
    $la['CITY'] = 'مدينة';
    $la['CONTACT_INFO'] = 'معلومات الاتصال';
    $la['NAME_SURNAME'] = 'الاسم واللقب';
    $la['POST_CODE'] = 'رمز آخر';
    $la['COUNTRY_STATE'] = 'مقاطعة / الدولة';
    $la['PHONE_NUMBER_1'] = 'رقم الهاتف 1';
    $la['PHONE_NUMBER_2'] = 'رقم الهاتف 2';
    $la['CHANGE_PASSWORD'] = "تغيير كلمة المرور";
    $la['OLD_PASSWORD'] = "كلمة المرور القديمة";
    $la['NEW_PASSWORD'] = "كلمة مرور جديدة";
    $la['REPEAT_NEW_PASSWORD'] = "تكرار كلمة مرور جديدة";
    $la['MY_ACCOUNT'] = 'حسابي';
    $la['SUB_ACCOUNTS'] = 'حسابات فرعية';
    $la['SUB_ACCOUNT'] = 'الحساب الفرعي';
    $la['EMAIL_ADDRESS'] = 'عنوان البريد الإلكتروني';
    $la['PHONE_NUMBER_WITH_CODE'] = 'رقم الهاتف مع رمز';
    $la['REMEMBER_ME'] = 'تذكرني';
    $la['SELECTED_OBJECTS'] = 'العربات المحددة';
    $la['SUB_ACCOUNT_PROPERTIES'] = 'خصائص الحساب الفرعي';
    $la['SUB_ACCOUNTS_CAN_SPLIT_THIS_ACCOUNT_INTO_MULTIPLE_SMALLER_ACCOUNTS'] = 'حسابات فرعية يمكن تقسيم هذا الحساب إلى حسابات أصغر متعددة مع امتيازات محدودة.';
    $la['CONTACT_ADMIN_IF_YOU_WANT_TO_DO_ANY_CHANGES'] = 'اتصل بمسؤول إذا كنت تريد أن تفعل أي تغييرات مع الأشياء الخاصة بك.';
    $la['NEWLY_ADDED_GPS_OBJECTS_CAN_BE_USED_FOR'] = "العربات المضافة حديثا يمكن استخدامها في {$gsValues['OBJ_TRIAL_PERIOD']} أيام مجانا.";
    $la['YOU_CAN_ADD'] = 'يمكنك إضافة';
    $la['GPS_OBJECTS_TILL'] = 'عربة حتى';
    $la['EXPAND_THIS_LIMIT_IN_OUR_SHOP'] = "توسيع هذا الحد في منطقتنا <a href='{$gsValues['URL_SHOP']}' target='_blank'>shop</a>."; 
    $la['YOU_CAN_ADD_UNLIMITED_NUMBER_OF_GPS_OBJECTS_TILL'] = 'يمكنك إضافة عدد غير محدود من العربات  حتى';
    $la['YOUR_SESSION_HAS_EXPIRED'] = "مدة تفعيل حسابك قد انتهت يرجى <a href='{$gsValues['URL_LOGIN']}'>login</a> مرة أخرى.";
    $la['SMS'] = "SMS";
    // account and personal
    
    // object
    $la['SEND_COMMAND'] = 'ارسال طلب';
    $la['OBJECT_LIST'] = 'لائحة العربات';
    $la['OBJECT'] = 'عربة';
    $la['OBJECTS'] = 'العربات';
    $la['IMEI'] = 'الرقم التسلسلي';
    $la['COMMAND'] = ' طلب';
    $la['COMMANDS'] = 'طلبات';
    $la['COMMANDS_STATUS'] = 'حالة الطلبات';
    $la['COMMAND_PROPERTIES'] = 'خصائص الطلب';
    $la['GROUP'] = ' مجموعة';
    $la['DRIVER'] = 'سائق';
    $la['ODOMETER'] = 'عداد المسافات';
    $la['ABSOLUTE_ODOMETER'] = 'عداد المسافات المطلقة';
    $la['RELATIVE_ODOMETER'] = 'عداد المسافات النسبية';
    $la['ABSOLUTE_ENGINE_HOURS'] = 'ساعات المحرك المطلقة';
    $la['RELATIVE_ENGINE_HOURS'] = 'ساعات المحرك النسبية';
    $la['SUMMER_RATE'] = 'معدل الصيف';
    $la['WINTER_RATE'] = 'معدل الشتاء';
    $la['WINTER_FROM'] = ' (الشتاء من (الشهر واليوم  ';
    $la['WINTER_TO'] = '(الشتاء من (الشهر واليوم';
    $la['TRANSPORT_MODEL'] = 'نوع العربة';
    $la['PLATE_NUMBER'] = 'لوحة ترقيم العربة';
    $la['SIM_CARD_NUMBER'] = 'رقم بطاقة SIM';
    $la['ENGINE_HOURS'] = 'ساعات المحرك';
    $la['GPS_DEVICE'] = 'جهاز GPS';
    $la['FUEL_CONSUMPTION'] = 'استهلاك الوقود';
    $la['AVAILABLE_OBJECTS'] = 'العربات المتوفرة';
    $la['SENSOR'] = 'الاستشعار';
    $la['SENSORS'] = 'أجهزة الاستشعار';
    $la['SENSOR_PROPERTIES'] = 'خصائص استشعار';
    $la['IGNITION_ACC'] = 'اشتعال (ACC)';
    $la['DIGITAL_INPUT'] = 'المدخلات الرقمية';
    $la['DIGITAL_OUTPUT'] = 'الإخراج الرقمي';
    $la['FUEL_LEVEL'] = 'مستوى الوقود';
    $la['PARAMETER'] = 'الضبط';
    $la['UNITS_OF_MEASUREMENT'] = 'وحدات القياس';
    $la['IF_SENSOR_1'] = ' (استشعار "1" (نص';
    $la['IF_SENSOR_0'] = '(استشعار "0" (نص';
    $la['LOWEST_VALUE'] = 'أدنى قيمة';
    $la['HIGHEST_VALUE'] = 'أعلى قيمة';
    $la['FORMULA'] = 'صيغة';
    $la['ACCURACY'] = 'دقة';
    $la['DETECT_STOPS_USING'] = 'الكشف عن توقف استخدام';
    $la['MIN_MOVING_SPEED'] = ' (دقيقة. سرعة التحرك في كم / ساعة (يؤثر توقف وتتبع الدقة، (الافتراضي 6)';
    $la['MIN_DIFF_BETWEEN_POINTS'] = ' (دقيقة. الفرق بين نقاط المسار (يزيل الانجراف، (الافتراضي 0.0005)';
    $la['MIN_GPSLEV_VALUE'] = 'دقيقة. قيمة gpslev (يزيل الانجراف، (الافتراضي 5)';
    $la['MAX_HDOP_VALUE'] = '(كحد أقصى. قيمة HDOP (يزيل الانجراف،(الافتراضي 3)';
    $la['MIN_FF'] = " (دقيقة. الفرق الوقود للكشف عن حشو الوقود (الافتراضي 10";
    $la['MIN_FT'] = " (دقيقة. الفرق الوقود لكشف السرقات الوقود (الافتراضي 10";
    $la['SERVICE'] = 'خدمة';
    $la['SERVICE_PROPERTIES'] = 'خصائص خدمة';
    $la['ODOMETER_INTERVAL'] = 'فاصل عداد المسافات';
    $la['ENGINE_HOURS_INTERVAL'] = 'فاصل ساعات المحرك';
    $la['DAYS_INTERVAL'] = 'فاصل أيام';
    $la['LAST_SERVICE'] = 'خدمة مشاركة';
    $la['CURRENT_OBJECT_COUNTERS'] = 'عدادات العربة الحالية';
    $la['CURRENT_ODOMETER'] = 'عداد المسافات الحالي';
    $la['CURRENT_ENGINE_HOURS'] = 'ساعات المحرك الحالي';
    $la['OBJECT_DRIVER_LIST'] = 'قائمة سائقي العربة';
    $la['OBJECT_DRIVER_PROPERTIES'] = 'خصائص قائمة سائقي العربة';
    $la['OBJECT_GROUP_LIST'] = 'قائمة مجموعة العربات';
    $la['OBJECT_GROUP_PROPERTIES'] = 'خصائص مجموعة العربات';
    $la['FIT_OBJECTS_ON_MAP'] = 'تزويد العربات على الخريطة';
    $la['NO_OBJECTS'] = 'لا عربات';
    $la['LOGIC'] = 'منطق';
    $la['STRING'] = 'سلسلة';
    $la['PERCENTAGE'] = 'نسبة مئوية';
    $la['PARAMETERS'] = "الضبط";
    $la['MODEL'] = "نموذج";
    $la['PLATE'] = "لوحة";
    $la['NO_DRIVER'] = "لا سائق";
    $la['ACTIVE_TILL'] = 'تفعيل حتى';
    $la['DRIVER_INFO'] = "معلومات السائق";  
    $la['CHECK_GPS_SIGNAL'] = 'تحقق إشارة GPS';
    $la['NO_DATA'] = "لا توجد بيانات";
    $la['NO_DATA_HAS_BEEN_RECEIVED_YET'] = "لم يتم تلقي أي بيانات من جهاز GPS حتى الآن.";
    $la['SENSOR_PARAMETERS_ARE_NOT_DETECTED_FOR_THIS_GPS_DEVICE'] = "لم يتم الكشف عن جهاز استشعار  لهذا الجهاز GPS حتى الآن.";
    $la['AT_LEAST_ONE_OBJECT_SELECTED'] = 'يجب تحديد عربة واحدة على الأقل.';
    $la['COMMAND_SENT_FOR_EXECUTION'] = "أرسلت الأوامر لتنفيذها بنجاح.";
    $la['INACTIVE_OBJECTS'] = "عربات غير نشطة";
    $la['THERE_ARE_INACTIVE_OBJECTS_IN_YOUR_ACCOUNT'] = 'هناك عربات غير نشطة في حسابك. انتقل إلى <a href="#" onclick="settingsOpen();">settings</a> لمزيد من التفاصيل.';
    $la['EXPIRING_OBJECTS'] = "أجهزة تنتهي مدة تفعيلها";
    $la['SOME_OF_YOUR_OBJECTS_ACTIVATION_WILL_EXPIRE_SOON'] = 'بعض اجهزتك ستنتهي مدة تفعيلها انتقل الى <a href="#" onclick="settingsOpen();">settings</a> لمزيد من التفاصيل';
    // object
    
    // places
    $la['PLACES'] = 'الأماكن';
    $la['ZONES'] = 'المناطق';
    $la['MARKERS'] = 'علامات';
    $la['ZONE_NAME'] = 'اسم المنطقة';
    $la['MARKER_PROPERTIES'] = 'خصائص علامة';
    $la['MARKER_VISIBLE'] = 'علامة مرئية';
    $la['ZONE_PROPERTIES'] = 'خصائص المنطقة';
    $la['ZONE_VISIBLE'] = 'منطقة مرئية';
    $la['NAME_VISIBLE'] = 'اسم مرئي';
    $la['AVAILABLE_ZONES'] = 'المناطق المتاحة';
    $la['AVAILABLE_MARKERS'] = 'علامات متاحة';
    $la['ADD_ZONE'] = 'إضافة منطقة';
    $la['ADD_MARKER'] = 'إضافة علامة';
    $la['NEW_ZONE'] = 'منطقة جديدة';
    $la['NEW_MARKER'] = 'علامة جديدة';  
    $la['NEAREST_ZONE'] = "أقرب منطقة";
    $la['NEAREST_MARKER'] = "أقرب علامة";
    $la['AT_LEAST_ONE_ZONE_SELECTED'] = 'يجب تحديد منطقة واحدة على الأقل.';
    $la['DRAW_ZONE_ON_MAP_BEFORE_SAVING'] = "رسم المنطقة على الخريطة قبل الحفظ.";
    $la['PLACE_MARKER_ON_MAP_BEFORE_SAVING'] = "وضع علامة على الخريطة قبل الحفظ.";
    // places
    
    // settings
    $la['TIMEZONE'] = 'منطقة زمنية';    
    $la['REMEMBER_MAP_POSITION'] = 'تذكر الموقف الاخير';
    $la['SHOW_OBJECT_TAIL'] = 'بيان مراقبة العربة';
    $la['OBJECT_TAIL_COLOR'] = 'لون العربة';
    $la['HISTORY_ROUTE_COLOR'] = 'لون الطريق';
    $la['HISTORY_ROUTE_HIGHLIGHT_COLOR'] = 'الطريق تسليط الضوء على اللون';
    $la['SHOWN_ICON_ON_MAP'] = 'أيقونة تظهر على الخريطة';
    $la['ADD_OBJECT'] = 'إضافة جهاز';
    $la['EDIT_OBJECT'] = 'تعديل الجهاز';
    $la['DUPLICATE_OBJECT'] = 'تكرار الجهاز';
    $la['SELECT_ICON'] = 'حدد رمز';
    $la['USER_INTERFACE'] = 'واجهة المستخدم';
    $la['CHANGES_SAVED_SUCCESSFULLY'] = 'التغييرات محفوظة بنجاح.';
    $la['SETTINGS_NOT_SAVED'] = 'لا يتم حفظ الإعدادات.';
    $la['PASSWORD_CANT_BE_EMPTY'] = "كلمة لا يمكن أن تكون فارغة.";
    $la['INCORRECT_PASSWORD'] = "كلمة مرور غير صحيحة.";
    $la['REPEATED_PASSWORD_IS_INCORRECT'] = "كلمة المتكررة غير صحيح.";
    $la['PASSWORD_LENGHT_AT_LEAST'] = "يجب أن يكون طول كلمة السر لا يقل عن 6 أحرف.";
    // settings
    
    // other
    $la['LOADING'] = 'تحميل ...';
    $la['ADD'] = 'إضافة';
    $la['SYSTEM'] = 'نظام';
    $la['CREATE'] = 'خلق';
    $la['HELLO'] = 'مرحبا';
    $la['CUSTOM'] = 'عرف';
    $la['MAIN'] = 'رئيسي';
    $la['NAME'] = 'اسم';
    $la['COLOR'] = 'لون';
    $la['ICON'] = 'رمز';
    $la['TYPE'] = 'نوع';
    $la['RESULT'] = 'نتيجة';
    $la['ABOUT'] = 'حول';
    $la['HELP'] = 'مساعدة';
    $la['RULER'] = 'مسيطر';
    $la['DESCRIPTION'] = 'وصف';
    $la['FORMAT'] = 'شكل';
    $la['UNGROUPED'] = 'فك تجميعها';
    $la['PER'] = 'per';
    $la['ACTIVATE'] = 'تفعيل';
    $la['ACTIVE'] = "تفعيل";
    $la['ARROW'] = 'سهم';
    $la['OTHER'] = 'آخر';
    $la['STATUS'] = 'حالة';
    $la['TOTAL'] = 'مجموع';
    $la['START'] = 'بداية';
    $la['END'] = 'نهاية';
    $la['SEND_TO_EMAIL'] = 'إرسالها إلى البريد الإلكتروني';
    $la['ENTER_CODE'] = 'إدخال رمز';
    $la['SHOW_POINT'] = 'تظهر نقطة';
    $la['ADDRESS_SEARCH'] = 'البحث عن عنوان';
    $la['ID_NUMBER'] = 'رقم';
    $la['CANT_SEND_EMAIL'] = "لا يمكن إرسال البريد الإلكتروني.";
    $la['CONTACT_ADMINISTRATOR'] = "اتصل بالمسؤول.";
    $la['NOTHING_HAS_BEEN_FOUND_ON_YOUR_REQUEST'] = 'لم يتم  العثو على طلبك.';
    $la['HOLD_CTRL_TO_SELECT_MULTIPLE_ITEMS'] = 'اضغط على "Ctrl" لتحديد عناصر متعدد';
    $la['SECURITY_CODE_IS_INCORRECT'] = 'رمز الأمان غير صحيح.';
    $la['ODOMETER_LEFT'] = 'عداد المسافات الى اليسار';
    $la['ODOMETER_EXPIRED'] = 'انتهت عداد المسافات';
    $la['ENGINE_HOURS_LEFT'] = 'انتهت عداد المسافات';
    $la['ENGINE_HOURS_EXPIRED'] = 'ساعات محرك انتهت';
    $la['DAYS_LEFT'] = 'ساعات محرك انتهت';
    $la['DAYS_EXPIRED'] = 'انتهت أيام';
    $la['DATA'] = "معطيات";
    $la['VALUE'] = "قيمة";
    $la['GENERAL'] = "عام";
    $la['INFORMATION'] = "معلومات";
    $la['ERROR'] = "خطأ";
    // other
    
    // invalid messages
    $la['INTERVAL_VALUE_SHOULD_BE_GREATER_THAN_LEFT_VALUE'] = "يجب أن تكون القيمة أكبر من قيمة الفاصل الى اليسار";
    $la['THERE_IS_NO_SUCH_OBJECT_IN_YOUR_ACCOUNT'] = "لا يوجد جهاز من هذا القبيل في حسابك.";
    $la['INVALID_FILE_FORMAT'] = "تنسيق ملف غير صالح.";    
    $la['THIS_EMAIL_IS_NOT_VALID'] = 'هذا البريد الإلكتروني غير صالح.';
    $la['COMMAND_HEX_NOT_VALID'] = " HEX الأمر غير صحيح.";
    $la['NAME_CANT_BE_EMPTY'] = "الإسم لا يمكن أن تكون فارغة.";
    $la['THIS_IMEI_IS_NOT_VALID'] = "هذا IMEI غير صالح";
    $la['COMMAND_CANT_BE_EMPTY'] = "الطلب لا يمكن أن يكون فارغا.";
    $la['SPEED_LIMIT_CANT_BE_EMPTY'] = "الحد الأقصى للسرعة لا يمكن أن تكون فارغة.";
    $la['ALL_AVAILABLE_FIELDS_SHOULD_BE_FILLED_OUT'] = "يجب ملء جميع الحقول المتوفرة بها.";
    $la['THIS_IMEI_ALREADY_EXISTS'] = "هذا IMEI موجود بالفعل.";
    $la['YOU_HAVE_REACHED_THE_LIMIT_OF_OBJECTS'] = 'لقد وصلت الى الحد الاقصى من الاجهزة';
    $la['THIS_ACCOUNT_HAS_NO_PRIVILEGES_TO_DO_THAT'] = "هذا الحساب ليس لديه امتيازات للقيام بأي تغييرات.";
    $la['NOTHING_HAS_BEEN_FOUND'] = "لم يتم العثور على طلبك.";
    $la['NOTHING_HAS_BEEN_FOUND_TO_IMPORT'] = "لم يتم العثور على طلبك للا ستيراد .";
    $la['IMPORT_FILE_IS_TOO_BIG'] = "ملف الاستيراد كبيرة جدا.";
    $la['IGNITION_SENSOR_IS_ALREADY_AVAILABLE'] = "استشعار الإشعال هو متاح بالفعل.";
    // invalid messages
    
    // questions
    $la['ARE_YOU_SURE_YOU_WANT_TO_OVERWRITE_SELECTED_COMMAND'] = "هل أنت متأكد أنك تريد كتابة الأمر المحدد؟";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE_ALL_EVENTS'] = "هل أنت متأكد أنك تريد حذف جميع الأحداث؟";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE_ALL_PLACES'] = "هل أنت متأكد أنك تريد حذف جميع الأماكن؟";
    $la['ARE_YOU_SURE_YOU_WANT_TO_DELETE'] = "هل أنت متأكد أنك تريد حذف";
    $la['ZONES_FOUND'] = 'المناطق الموجودة';
    $la['MARKERS_FOUND'] = 'علامات وجدت.';
    $la['ARE_YOU_SURE_YOU_WANT_TO_IMPORT'] = "هل أنت متأكد أنك تريد استيراده؟";
    // questions
?>